### ISSUE TITLE
Documentation of Python bindings

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#106]
I have tried the Python bindings, it seems to work well on my computer.
I did not try yet with Pinocchio, but I may give it a try next week.

In the meantime, I think it should be nice to provide the documentation with the main FCL geometries. @jmirabel Have you tried your script to automatize the documentation?

**Comment by jmirabel** [comment]
I have something which works reasonably well, with the following drawbacks:
- it's a labyrinthine system that's gonna be hard to maintain (some kind of ro code...).
- handling CRTP will be very hard, if possible at all.

I will try to propose something in an (yet undefined) future.

**Comment by jcarpent** [comment]
Thanks a lot for the quick reply. We can wait indeed. But, maybe we can put some manual documentation for standard primitives to help new users.

**Comment by jmirabel** [comment]
I can add the generated files as a first step.

**Comment by jmirabel** [comment]
@jcarpent , you may want to try the documentation on my branch python_doc.

You must add my fork of the JRL cmake module it order for it to work.

**Comment by rstrudel** [comment]
Hi,

I do agree it would be nice to get more readable documentation. The typical output I get in python is:
`
In [4]: hppfcl.Sphere?                                                                                                                                                                                                                        
Docstring:      <no docstring>
Init docstring:
__init__( (object)arg1, (float)arg2) -> None :

    C++ signature :
        void __init__(_object*,double)
File:           ~/miniconda3/envs/robot/lib/python3.7/site-packages/hppfcl/hppfcl.cpython-37m-x86_64-linux-gnu.so
Type:           class
Subclasses
`

Whereas when I read the file exposing the shapes [collision-geometries.cc](https://github.com/humanoid-path-planner/hpp-fcl/blob/devel/python/collision-geometries.cc), it is well written and self explanatory. Sorry for the newbie/uninformed question, what is missing to get something that looks like the actual function signature in python ?

**Comment by jmirabel** [comment]
I'll try to work on this.

**Comment by rstrudel** [comment]
Thank you @jmirabel , I understand this is time consuming and that it is not really a priority. I have a limited knowledge of the repo and C++/python bindings in general but let me know if I can help at some point.

**Comment by jmirabel** [comment]
@rstrudel A review of #129 is welcome.

**Comment by jcarpent** [comment]
I've tried the generation of the documentation from doxygen on Mac, but it fails with the following error:
```
Error: /undefined in getenv
Operand stack:
   (outfile)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1974   1   4   %oparray_pop   1973   1   4   %oparray_pop   1961   1   4   %oparray_pop   1817   1   4   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:727/1123(ro)(G)--   --dict:0/20(G)--   --dict:76/200(L)--   --dict:5/30(L)--   --dict:11/30(L)--
Current allocation mode is local
Current file position is 8386
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
```

**Comment by jmirabel** [comment]
Which software complains ?

**Comment by jcarpent** [comment]
When generating the documentation. 
Just to be sure, how do you link the Python doc to the doxygen doc? What are the different steps?

**Comment by jmirabel** [comment]
1. Doxygen generates the documention in XML format (folder build/doc/doxygen-xml)
2. Python script doc/python/doxygen_xml_parser.py, which generates a set of C++ files.
3. The bindings includes the C++ generated files.

**Comment by jcarpent** [comment]
Then, how to launch all those steps ?

**Comment by jmirabel** [comment]
In the root of the build folder:
1. make doc
2. make generate_doxygen_cpp_doc
3. make -C python

**Comment by jcarpent** [comment]
Who is generating `generate_doxygen_cpp_doc` target?

**Comment by jmirabel** [comment]
python/CMakeLists.txt

**Comment by jmirabel** [comment]
`VERBOSE=1 make ...` will display the command before executing it. It may help you.

**Comment by jmirabel** [comment]
The C++ generated files are in build/python/doxygen_autodoc folder.

**Comment by jcarpent** [comment]
OK. Sounds good. I see now.

**Comment by jcarpent** [comment]
Seems good and solved. Thanks @jmirabel for your answers.
