### ISSUE TITLE
Enable Python bindings detection by cmake

### ISSUE THREAD

**Issue by gabrielebndn** [humanoid-path-planner/hpp-fcl#122]
I think it would be useful to allow other packages to detect via cmake whether the Python bindings are installed or not (see for instance stack-of-tasks/pinocchio/issues/1005).

In Pinocchio, an additional pc file is installed with the bindings: see [bindings/python/pinocchiopy.pc.cmake](https://github.com/stack-of-tasks/pinocchio/blob/e038c7bf283b1df56a35014455e0e2d6f36e03ac/bindings/python/pinocchiopy.pc.cmake). Should we do something similar in hpp-fcl? Or maybe use cmake export?

**Comment by jcarpent** [comment]
We do need to do like in Pinocchio. Indeed, the case of Pinocchio is particular for the SoT.

**Comment by jcarpent** [comment]
Solved by #121.

**Comment by gabrielebndn** [comment]
> Solved by #121.

@jcarpent, I think there is a mistake here, #121 has nothing to do with this issue. Was closing it correct?

**Comment by nim65s** [comment]
If the python bindings are always enabled (#121), we don't need to detect if there are enabled or not. 

They might be manually turned off, but if someone does that, we can expect them to know it.

**Comment by gabrielebndn** [comment]
So for the concrete case of Pinocchio:
Supporting the case `BUILD_PYTHON_INTERFACE=ON` `BUILD_WITH_COLLISION_SUPPORT=ON` but hpp-fcl bindings absent is a useless complication.
The alternative is that in Python when `BUILD_WITH_COLLISION_SUPPORT=ON` we just assume  the package `hppfcl` is installed too and simply fail when `import hppfcl` is done. I guess this could be acceptable.
I guess this would be acceptable -- just install the missing package. @nim65s is this what you mean?
