### ISSUE TITLE
Collision with volume / closed-shape object

### ISSUE THREAD

**Issue by pFernbach** [humanoid-path-planner/hpp-fcl#134]
Hello,
I know that this is old news and we already talked about but it was never solved and became relevant again in some of my new use cases.

FCL do not have any notion of "volume" or closed-shape object, it only test collision between the surfaces of the pair of object. If one of the object in entirely inside the other, it doesn't detect the collision. 

Is there any ongoing development to change this ?

**Comment by jmirabel** [comment]
Summary of the oral discussion with @pFernbach:

If the objects are convex, then hpp-fcl can do this. You must use the shape class Convex. As of now, it should be used with care because it hasn't been heavily used yet.
