### ISSUE TITLE
Confusing tag v4.4.0-rc

### ISSUE THREAD

**Issue by gabrielebndn** [humanoid-path-planner/hpp-fcl#143]
Hi all,
while downloading and building from source, in search for the latest stable release, I noticed a very confusing tag `v4.4.0-rc`: https://github.com/humanoid-path-planner/hpp-fcl/tree/v4.4.0-rc.

What makes it confusing is that it the latest release is `1.3.0`, and also `v4.4.0-rc` seems to be very old, from 26/02/2019. It was probably a mistake.

Should it be deleted? I am not sure whether I have access rights to do it, and even if I did I do not dare to delete it before being 100% sure it is the right thing to do.

**Comment by jmirabel** [comment]
At some point, we though of homogenizing the version numbers of all HPP packages. We changed our mind for hpp-fcl (and I don't know whether the policy has been enforced since then) because there would anyway have been pinocchio in between not following HPP version numbers.

I don't mind it being deleted.

**Comment by nim65s** [comment]
I already deleted it several times, but someone keep pushing it, I think unintentionaly.

**Comment by gabrielebndn** [comment]
@nim65s I see. We should be careful to remove it from our forks and local copies too, then. I see a `v4.5.0-rc` too

**Comment by jmirabel** [comment]
We all agree to delete it so I guess we can close this.

**Comment by jmirabel** [comment]
And it is not on my fork.

**Comment by nim65s** [comment]
I just removed again the tags `4.5.0-rc` & `v4.4.0-rc`. Someone keeps pushing those ^^"

Please mind that you can `git push vX.Y.Z` to push one tag, instead of `git push --tags`, to push all your local tags.
