### ISSUE TITLE
Returning several contact points for basic Shape collision

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#144]
In some cases like simulation, it would be essential to return all the collision points between two basic shapes. For instance, a box against an half-space in contact will return the four vertices of the box face in contact.

@jmirabel, @florent-lamiraux What do you think?

**Comment by florent-lamiraux** [comment]
You need to better define what you expect to be returned. In the case you mention, the contact is a square surface, not only 4 points.

**Comment by rayzchen** [comment]
If I use Python:

```
import hppfcl
import numpy as np

s1 = hppfcl.Box(2, 2, 2)
s2 = hppfcl.Box(2, 2, 2)
o1 = hppfcl.CollisionObject(s1)
o2 = hppfcl.CollisionObject(s2)
o2.setTranslation(np.array([1.9999, 0, 0]))
req = hppfcl.CollisionRequest()
req.num_max_contacts = 4
res = hppfcl.CollisionResult()
print(hppfcl.collide(o1, o2, req, res))
print(hppfcl.getContact(0).pos)
```

Why does this return only 1 contact? And why is that contact at (0.995, -1, -1) which is in the corner of the colliding surface? In my physics engine, it's causing the two boxes to rotate in an awkward way that just pushes them into each other, causing more collisions, causing a larger intersection volume in a vicious cycle. Shouldn't there be 4 contacts for each corner? Or at least 1 contact that is somewhere around (0.995, 0, 0)? Am I understanding the notion of a contact wrong?

**Comment by jcarpent** [comment]
You're correct. The thing is that current GJK algorithm used for collision detection between two boxes only returns one contact point, not several.
The contact point information corresponds to the average of the two witness points resulting from the collision detection algorithm.

**Comment by rayzchen** [comment]
How would I get a more accurate point of collision then?

**Comment by jmirabel** [comment]
You must use the penetration information. Make distance requests and make sure the nearest point calculations are enabled.

**Comment by rayzchen** [comment]
```python3
import hppfcl
import numpy as np

s1 = hppfcl.Box(2, 2, 2)
s2 = hppfcl.Box(2, 2, 2)
o1 = hppfcl.CollisionObject(s1)
o2 = hppfcl.CollisionObject(s2)
o1.setTranslation(np.array([1.9999999, 0, 0]))
req = hppfcl.DistanceRequest()
req.enable_nearest_points = True
res = hppfcl.DistanceResult()
hppfcl.distance(o1, o2, req, res)
print(res.normal)
print(res.min_distance)
print((res.getNearestPoint1() + res.getNearestPoint2()) / 2)
```
Output:
```
[6.95312428e-310 6.95312277e-310 0.00000000e+000]
-1.7976931348623157e+308
[ 0.99999995 -1.00000001 -1.00000001]
```

Why is the min_distance so large? And the nearest point is still in a corner of the surface. What does the normal represent in this case?

**Comment by rayzchen** [comment]
Changing line 8 to use 1.9999 instead of 1.9999999 makes the normal and min_distance more sensical.

**Comment by lmontaut** [comment]
The min_d is very large because the output simplex of GJK before entering in EPA is of rank 1. EPA goes in to 'FallBack' mode and the default behavior is to return a - infinity distance. However it should just return 0. I will do a PR later during the day to fix that

**Comment by lmontaut** [comment]
EPA exiting in fallback mode means that we have a vertex-vertex collision. The normal is by definition undefined (there is a cone of possible normals). Hppfcl currently does not have a strategy to deal with this scenario but we are working on it

**Comment by rayzchen** [comment]
So how would I get an expected point of collision of `[0.99999995 0.0 0.0]`?

**Comment by jmirabel** [comment]
EPA is subject to numerical issues (at least the implementation in this project. The problem you hit is due to the *very unlikely* case where objects have exactly parallel faces. I encountered this when I worked on GJK and EPA some years ago. In comparison, GJK is fairly more stable numerically (at least in this project). I could not find a neat way of handling this case. Add a very small rotation to any of the boxes and I think you won't have any issues.

**Comment by rayzchen** [comment]
Could I handle this as a sort of edge case by detecting if two faces are perfectly parallel and setting the point of collision to a sort of average center of the sides?

**Comment by rayzchen** [comment]
> EDIT 2: If this is critical for you and you can't afford failures, you should make sure your requests rely on GJK (e.g. using shape inflation).
How does this work differently?

**Comment by lmontaut** [comment]
> Could I handle this as a sort of edge case by detecting if two faces are perfectly parallel and setting the point of collision to a sort of average center of the sides?

Unfortunately no. One of the ways to properly define the contact point would be to take the barycenter of the contact area. But when two faces are in contact, the contact area of a face is not necessarily the entire face but often only a portion of it.

**Comment by jcarpent** [comment]
> > EDIT 2: If this is critical for you and you can't afford failures, you should make sure your requests rely on GJK (e.g. using shape inflation).
> 
> How does this work differently? And how would I go about doing this? Doesn't GJK only find if the origin is inside the Minkowski difference?

When there is a penetration (detected by GJK), then EPA is called to retrieve the penetration depth.

**Comment by jmirabel** [comment]
What I have in mind is slightly different. GJK is able to compute the penetration information when the penetration is inferior to the inflation.

The inflation consist in making a sphere of some fixed radius (the inflation) on your convex shape. E.g. a sphere is an inflated point. A capsule is an inflated line segment.
GJK will work with the non inflated shape. If the two inflated shapes overlap but the non inflated shapes do not overlap, then GJK can compute the penetration for the inflated shapes. When the non inflated shapes overlap, then EPA is used after GJK.

Note: the inflation of two inflated shapes is the sum of the inflation of each shape.

**Comment by jmirabel** [comment]
So if you expect your object to never overlap more than 1cm, then using an inflation of 5mm will make hpp-fcl use only GJK.

**Comment by rayzchen** [comment]
How do I set the inflation? All I can find is an `inflation` attribute on the `MinkowskiDiff` struct.

**Comment by lmontaut** [comment]
The inflation is set by using a positive security margin:
```
req = hppfcl.CollisionRequest()
res.security_margin = 1e-2
```

**Comment by rayzchen** [comment]
> EDIT 2: If this is critical for you and you can't afford failures, you should make sure your requests rely on GJK (e.g. using shape inflation).

I'm not quite sure what you mean by this, what would using shape inflation do to help?
P.S setting a security margin yields the same values.

**Comment by lmontaut** [comment]
```
o1.setTranslation(np.array([1.9999999 + security_margin, 0, 0]))
```

**Comment by jmirabel** [comment]
Hum, true, at the moment, we use the inflation only for sphere and capsules.

At some point, we should consider having inflation in `ShapeBase`.

**Comment by rayzchen** [comment]
> ```
> o1.setTranslation(np.array([1.9999999 + security_margin, 0, 0]))
> ```

How would this work when i take any two arbitrary transforms? How would I adjust for security margin?

**Comment by jcarpent** [comment]
> Hum, true, at the moment, we use the inflation only for sphere and capsules.
> 
> At some point, we should consider having inflation in `ShapeBase`.

For info, I've recently added the `inflated` methods to the most common basic shapes.
