### ISSUE TITLE
huge test resources

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-fcl#151]
Hi,

test/fcl_resources is 55.4 Mo.
Are these files really required ?

If so, `tar --zstd -cvf fcl_resources.tar.zst fcl_resources/` is 6.9 Mo, and would reduce the release tarball from 11Mo to 7.5Mo, so maybe we should consider compressing those.

(we could also decide to use zstd for our release tarballs instead of gz, but it will not be compatible with older systems)

**Comment by jmirabel** [comment]
```bash
$ du -h
2,6M	./manyframes
12M	./scenario-1-2-3
7,6M	./newdata
56M	.
```
I think the 3 folders inside can be removed. Then,
```
total 35M
-rw-r--r-- 1 jmirabel jmirabel  34M janv. 25 13:03 env.octree
-rw-r--r-- 1 jmirabel jmirabel 182K janv. 25 13:03 env.obj
-rw-r--r-- 1 jmirabel jmirabel  83K avril  3 11:20 staircases_koroibot_hr.dae
-rw-r--r-- 1 jmirabel jmirabel  16K janv. 25 13:03 rob.obj
-rw-r--r-- 1 jmirabel jmirabel 1,8K janv. 25 13:03 config.h.in
```
The env.octree could be stored using Octomap binary format. In this format, it only takes 888K.

**Comment by nim65s** [comment]
Release tarballs:
- 1.4.0: 10.8Mo
- 1.4.1: 1.19Mo. 
Good job :D
