### ISSUE TITLE
hpp-fcl is now dependent on assimp and pkg-config

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-fcl#16]
I don't agree with both dependencies,
especially the one on pkg-config,
which is unnecessary and prevents any user friendly external use of hpp-fcl
by other people than laas

**Comment by jmirabel** [comment]
What do you mean by prevent ?

- we should probably update the install instruction to have `sudo apt-get install libassimp-dev`,
- Assimp could be an optionnal dependency (but Pinocchio requires hpp-fcl with assimp)

**Comment by stonneau** [comment]
I'll rephrase, sorry.

I believe assimp is essentially not required by fcl, regarding its purpose as a collision detection library.
I don't believe the code that uses assimp should be in hpp-fcl

**Comment by nmansard** [comment]
We agreed on that, in principle. However, it also requires the creation of a trivial package containing a single method. 
To keep stuff simple in Gepetto, I suggest to have assimp as a conditional dependency in hpp-fcl, and as a strict dependency in Pinocchio.
