### ISSUE TITLE
Intersection volume of 2 meshes

### ISSUE THREAD

**Issue by edwardchaos** [humanoid-path-planner/hpp-fcl#162]
Goal: retrieve the intersection volume of 2 meshes if collisionResult.isCollision() returns true.

I have found the boolean capacity of whether meshes are colliding and also the computeDistances function where the distance between the 2 closest points can be queried.

Is there also provided api for the intersection volume or some way of quantifying the magnitude of 2 meshes intersecting?

I've found that the computeDistances function will always return a negative value close to 0 when 2 meshes partially intersect. This makes sense as the distance is only between the closest vertices on the meshes.

**Comment by jmirabel** [comment]
First of all, mind that your question makes sense only for shapes whose interior is defined. This is not the case of shapes stored by BVH. This type of shapes is a surface only so there is no volume of intersection for them. This is also why you always get a very small penetration depth (the minimum distance).

In hpp-fcl, all the shapes with volume are convex. All of them *should* return a correct penetration depth. In the general case, when feasible, it would be very costly to compute the exact intersection. A volume included in the intersection could iteratively be built using the support function but this is not implemented.
