### ISSUE TITLE
Area of contact between 2 meshes

### ISSUE THREAD

**Issue by edwardchaos** [humanoid-path-planner/hpp-fcl#163]
Goal: Quantify the area between meshes in contact

Hopefully your expert opinion can provide some insight on how this can be achieved using this library. 
If 2 meshes are in contact, is there a simple way to compute the contact area?

**Comment by jmirabel** [comment]
This is related to #144 and #162 .

This question is also not well defined.

For a soup of triangle against any other shape, it would be possible to return the list of triangle in contact. I think you can already has this by setting the maximum number of contacts to something very big (> number of triangles). For their, if you want the exact area, you have to implement the triangle against the other shape intersection.

For two shapes with volume (all shapes except BVH), I don't know what an area of contact would be.
