### ISSUE TITLE
Few unittests fails with `-march=native`

### ISSUE THREAD

**Issue by cmastalli** [humanoid-path-planner/hpp-fcl#166]
This is the list of unittest that are failing:
```bash
The following tests FAILED:
	  2 - collision (Failed)
	  3 - distance (Failed)
	  4 - distance_lower_bound (Failed)
	  5 - geometric_shapes (Failed)
	  6 - frontlist (Failed)
	 14 - bvh_models (Failed)
	 15 - profiling (SEGFAULT)
	 17 - octree (Failed)
```
Is this library supporting data alignment?

**Comment by jmirabel** [comment]
At least it did the last time I tried.

**Comment by jmirabel** [comment]
Everything works fine on my computer.

I think you got fooled by the linker. If you have hpp-fcl installed and accessible through your LD_LIBRARY_PATH, then the test will find first the installed version, not the compiled one. Hence the failures.

**Comment by cmastalli** [comment]
@jmirabel You're right! When I uninstalled `hpp-fcl`, I encountered that all unittests were passing.

Sorry for the distraction. I didn't think that was important to uninstall `hpp-fcl`.
