### ISSUE TITLE
Sync with official FCL repository

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#17]
FCL is moving forward and now integrates Eigen as spatial core module (flexible-collision-library/fcl/pull/150). We might think a bit to merge our current branch with the official one.

**Comment by nim65s** [comment]
@florent-lamiraux & @jmirabel will check if this is possible to merge hpp-fcl back into fcl. Otherwise, we will decide that hpp-fcl is a real fork and always will be.

**Comment by nim65s** [comment]
It seems that 3e3c3a2 is the last common commit.
```
hpp-fcl$ git diff --no-color 3e3c3a2 |grep -c  '^+'
22538
fcl$ git diff --no-color 3e3c3a2 |grep -c '^+'
129304
```
In other words, we made ~20k additions / modifications while they made ~130k additions / modifications.

**Comment by jcarpent** [comment]
I come back with this now old issue. 
@florent-lamiraux @jmirabel Would it possible to reconnect our projects with the official versions which seems now more mature and advance than ours?

**Comment by jmirabel** [comment]
The idea is appealing. It requires some work which does not have a high priority at the moment.

**Comment by florent-lamiraux** [comment]
I also mean moving forward to C++11.

**Comment by jcarpent** [comment]
That also something which is currently happening in Pinocchio for derivatives.

**Comment by jmirabel** [comment]
This will likely not happen, at least in a near future.
