### ISSUE TITLE
Supporting Windows

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#173]
In order to allow the full support of Pinocchio on Windows system, I would like to make this package compliant with Windows too, knowing that EigenPy is already working on Windows.

The main requested feature required is the export of all the functions and classes located in the shared library. This is not very complicated to do, so I was wondering who is willing to handle this task?

**Comment by jmirabel** [comment]
The following awk script can be used to handle structs and classes:
```awk
BEGIN {
handled = 0
}
/^\s*struct (\w+)/ {
  handled = 1
  if ($0 !~ /;/) {
    $1 = $1" HPP_FCL_DLLAPI"
  }
  print $0
}
/^\s*class (\w+)/ {
  handled = 1
  if ($0 !~ /;/) {
    $1 = $1" HPP_FCL_DLLAPI"
  }
  print $0
}
{
  if (handled == 0) { print $0 }
  handled = 0
}
```
It can be ran with `find include/ -type f -exec gawk -i inplace -f awk {} \;`.
Sadly, I don't know how to preserve the leading spaces. @nim65s do you know how to do it ?

**Comment by nim65s** [comment]
I'm not an expert with awk, but we could easily workaround this space issue with an auto-formatting tool ran after your script ;)

**Comment by jmirabel** [comment]
@nim65s branch *windows* on my fork applies the above script + misc. If it is quick for you, could you remove the spurious space changes ?

**Comment by jmirabel** [comment]
From g++ manual page:

        -fvisibility-ms-compat
           This flag attempts to use visibility settings to make GCC's C++ linkage model compatible with that of Microsoft Visual Studio.

           The flag makes these changes to GCC's linkage model:

           1.  It sets the default visibility to "hidden", like -fvisibility=hidden.

           2.  Types, but not their members, are not hidden by default.

           3.  The One Definition Rule is relaxed for types without explicit visibility specifications that are defined in more than one shared object: those declarations are permitted if they are
               permitted when this option is not used.


           In new code it is better to use -fvisibility=hidden and export those classes that are intended to be externally visible.  Unfortunately it is possible for code to rely, perhaps accidentally, on
           the Visual Studio behavior.

           Among the consequences of these changes are that static data members of the same type with the same name but defined in different shared objects are different, so changing one does not change
           the other; and that pointers to function members defined in different shared objects may not compare equal.  When this flag is given, it is a violation of the ODR to define types with the same
           name differently.

So adding option -fvisibility-ms-compat to g++ should help us test on linux the behaviour on windows.

**Comment by nim65s** [comment]
@jmirabel : https://github.com/nim65s/hpp-fcl/commit/718d1d26074afa92c93440bdad512472f8b23406 I think this should do
