### ISSUE TITLE
Latest release on robotpkg apt repository

### ISSUE THREAD

**Issue by duburcqa** [humanoid-path-planner/hpp-fcl#188]
Would it be possible to "upload" the latest release 1.5.3 on robotpkg repository (compatible with the latest Pinocchio release) ? It seems many changes have been introduced since the latest available one 1.4.5.

**Comment by nim65s** [comment]
I'm already working on it :)

**Comment by duburcqa** [comment]
Nice ! Thanks you :)

**Comment by jcarpent** [comment]
@duburcqa For fast release, you should rather use Conda which is working for Windows, Mac OS X and of course Linux.

**Comment by jcarpent** [comment]
I close this issue as a new release is in preparation.
