### ISSUE TITLE
Impossible to compute collision between convex and halfspace

### ISSUE THREAD

**Issue by duburcqa** [humanoid-path-planner/hpp-fcl#189]
- Trying to compute the collision between a convex geometry and an halfspace primitive through an exception
- The normal of the contact between a convex geometry and a box is always the one of the box, never the one of the convex geometry, no matter of their order in the collision pair. I'm not sure if it is intended and how to get the normal wrt the convex geometry.

NB: In Python, trying to access o1 from a CollisionResult raises an exception on my setup:
`No to_python (by-value) converter found for C++ type: hpp::fcl::CollisionGeometry const*`

**Comment by duburcqa** [comment]
Also, do you know why I get such contact points / nearest points when computing the collision between a mesh geometry and a box ? 

In the figure, I'm computing the collision with the feet and a square box of size 2.0 centered and aligned with the origin:
![image](https://user-images.githubusercontent.com/17752950/92948805-4334f700-f45a-11ea-850d-2acd90f8c2df.png)

I would expect the contact points to be on the feet, but it is not the case. I don't have such issue when computing the collision with halfspace.

**Comment by jcarpent** [comment]
Sorry but this issue is really unclear. Please clean it before we provide you an answer.

**Comment by duburcqa** [comment]
@jcarpent Sure no problem. I edited it. It should be more clear.

**Comment by florent-lamiraux** [comment]
Can you provide some sample code so that we can try to reproduce the issue ?

**Comment by jmirabel** [comment]
> Trying to compute the collision between a convex geometry and an halfspace primitive through an exception

I never used this so I am not completely surprised that it throws something. I'll have a look quickly to see if it is easy to fix.

>     * The normal of the contact between a convex geometry and a box is always the one of the box, never the one of the convex geometry, no matter of their order in the collision pair.

*always* is surprising (depending on what your convex shape is). The normal is defined as the direction that yields the smallest translation to get out of collision. If you have a box which is big wrt the convex mesh, then, yes, I expect the normal to be one of the box normals.

>  I'm not sure if it is intended and how to get the normal wrt the convex geometry.

Not sure whether this makes sense because a) this normal does not exist when the most penetrating point is a vertex and b) does not yield a satisfactory direction.
What do you want to do exactly ?

**Comment by jcarpent** [comment]
For the normal, I would say in the context of CONVEX vs BASIC PRIMITIVES, the solver should return a unique normal, which is easily defined for primitives, harder for meshes.

**Comment by jmirabel** [comment]
> > Trying to compute the collision between a convex geometry and an halfspace primitive through an exception
> 
> I never used this so I am not completely surprised that it throws something. I'll have a look quickly to see if it is easy to fix.

I misread your question and now have the correct answer.

Yes, I know it is not implemented although the implementation is trivial. One only has to call the GJK support function along half space direction.

**Comment by jmirabel** [comment]
> For the normal, I would say in the context of CONVEX vs BASIC PRIMITIVES, the solver should return a unique normal, which is easily defined for primitives, harder for meshes.

The term *normal* mislead you. The returned normal is the normal of the Minkowski difference at the point which is the closest to the origin.

**Comment by jcarpent** [comment]
@jmirabel I think the normal that @duburcqa refers is the contact normal in:

>     * The normal of the contact between a convex geometry and a box is always the one of the box, never the one of the convex geometry, no matter of their order in the collision pair. I'm not sure if it is intended and how to get the normal wrt the convex geometry.

**Comment by jmirabel** [comment]
@jcarpent got it. Thanks for the clarification.

**Comment by jcarpent** [comment]
Solved by #191.

**Comment by jmirabel** [comment]
>     * The normal of the contact between a convex geometry and a box is always the one of the box, never the one of the convex geometry, no matter of their order in the collision pair. I'm not sure if it is intended and how to get the normal wrt the convex geometry.

On this point, looking at the code, the contact normal is computed using GJK so it corresponds to what I described earlier. Do you have a minimal reproducible example of your case ?

**Comment by jmirabel** [comment]
The following code clearly shows that you don't always get the normal of the box:
```python
import hppfcl
hppfcl.switchToNumpyArray()
import numpy as np

def tetahedron():
    pts = hppfcl.StdVec_Vec3f()
    pts.append( np.array((0, 0, 0)) )
    pts.append( np.array((0, 1, 0)) )
    pts.append( np.array((1, 0, 0)) )
    pts.append( np.array((0, 0, 1)) )
    tri = hppfcl.StdVec_Triangle()
    tri.append(hppfcl.Triangle(0,1,2))
    tri.append(hppfcl.Triangle(0,1,3))
    tri.append(hppfcl.Triangle(0,2,3))
    tri.append(hppfcl.Triangle(1,2,3))
    return hppfcl.Convex(pts, tri)

def random_transform(scale=1.):
    from eigenpy import AngleAxis
    from random import random
    from math import pi
    M = hppfcl.Transform3f(
            AngleAxis(random() * pi, np.array([1,0,0])).matrix()
            @ AngleAxis(random() * pi, np.array([0,1,0])).matrix()
            @ AngleAxis(random() * pi, np.array([0,0,1])).matrix(),
            2*scale*(np.random.random(3)-0.5))
    return M


convex = tetahedron()
box = hppfcl.Box(np.array((1,1,1)))

req=hppfcl.CollisionRequest()
res=hppfcl.CollisionResult()

M1 = hppfcl.Transform3f()
for _ in range(10):
    M2 = random_transform(0.1)
    res.clear()
    if hppfcl.collide(convex, M1, box, M2, req, res) > 0:
        c = res.getContact(0)
        print("----")
        print("world", c.normal)
        print("box frame", M2.getRotation().T @ c.normal)
```

**Comment by duburcqa** [comment]
Hum, this is strange. I will check on my particular application.
