### ISSUE TITLE
Method impossible to call from Python

### ISSUE THREAD

**Issue by duburcqa** [humanoid-path-planner/hpp-fcl#199]
Hi,

AFAIK, `CollisionObject` is not exposed in Python, so it is impossible to call this method: https://github.com/humanoid-path-planner/hpp-fcl/blob/e63c349201297ef46ef651ca1e7883a7d4ab2571/python/distance.cc#L129

If I'm right, I suggest either to expose `CollisionObject` or to remove it ? The same goes for collisions.

Best

**Comment by jmirabel** [comment]
You are right, this overload isn't accessible.
I am not sure of the benefit of CollisionObject but since it exists in c++, it could be exposed in Python.

**Comment by duburcqa** [comment]
I must admit I like it because in practice for my application one of the geometry is fixed, so it avoids me passing systematically the same transform (even though it is the same internally). And to my view, it is closing the Pinocchio way of thinking (aka Model/Data).

**Comment by duburcqa** [comment]
Also since I'm here, I would like to point out the fact that `fcl::Octree` are not exposed in Python 

https://github.com/humanoid-path-planner/hpp-fcl/blob/a140097eb8ba171a807ac76009747a3e356fc93f/python/collision-geometries.cc#L416

So they appears as `CollisionGeometry`, making impossible to call some useful Octree-specific methods, especially `toBoxes`. But it is another issue not related to this one.

**Comment by jmirabel** [comment]
Are you wiling to propose a PR exposing CollisionObject and Octree ?

**Comment by duburcqa** [comment]
Not really for now. I'm not using hppfcl in Python. I was just trying to do some quick prototyping when I noticed those limitations.

**Comment by jmirabel** [comment]
CollisionObject has been exposed in #212
