### ISSUE TITLE
Package not distributed with qhull on robotpkg

### ISSUE THREAD

**Issue by duburcqa** [humanoid-path-planner/hpp-fcl#201]
Hi,

I just noticed that `hpp-fcl` is not distributed  with `qhull` on `robotpkg` apt-repository, at least for the latest release available. Is it intended ? Personnally, I rely on `qhull` for computing convex hulls and it would be helpful to get it directly without building `hpp-fcl` from source.

Best regards,
Alexis Duburcq

**Comment by nim65s** [comment]
Hi @duburcqa,

I already said I would do it, but this was burried in #167. Thanks for the heads-up, I'll work on that soon.

**Comment by duburcqa** [comment]
Arf I haven't checked the closed issues.  Sorry for the noise. I happy to hear it is on the todo-list !

**Comment by jmirabel** [comment]
@nim65s has this been done ?

**Comment by nim65s** [comment]
not yet, sorry for the delay

**Comment by nim65s** [comment]
fixed in https://github.com/nim65s/robotpkg/commit/0ce391c00588c4f906083a13ff3038e95f691920
