### ISSUE TITLE
Manager and self-collision check

### ISSUE THREAD

**Issue by dBierni** [humanoid-path-planner/hpp-fcl#211]
Hi!

I did some test with `hpp::fcl::collide` and seems it performs better than my current library. Additionally, I need support for PointCloud and a safety margin. 

So now, as the base `fcl` has a `BroadPhaseManagers`, I would ask if here I can find any support to check collision for multiple objects? - As I understand it should be not a big deal for me to adapt it to `fcl::BroadPhaseManagers`, cuz anyway improvements and safety margin are in `hpp::fcl::collide`?

Depending on an answer to the previous question,  I have also something like AllowedCollisionMatrix or Collision Pairs, between which I either want or not to check the collision.  So in `fcl` I would do this with `Callbacks` and `UserData`.  What about the `hpp::fcl` ?

The fact of a manager, I guess is the least invasive way for me to use the library right now.
Of course, I can do a vector of objects and check one against another, but the question is if there is any other way to check collision for multiple objects and self-collision.

Do you have any sample code? -  in the [test](https://github.com/humanoid-path-planner/hpp-core/tree/master/tests) folder I only see the very old ones. 

I consider both `discrete` and `continuous` collision checking.

**Comment by florent-lamiraux** [comment]
If each object follows a known trajectory and you want to test all possible pairs along this trajectory, then you can use `hpp-core` that implements continuous collision checking in an efficient way on top of `hpp-fcl`. Can you describe your problem a little bit more?

**Comment by jcarpent** [comment]
By the way, we are planning to transfer a part of continuous/discrete collision checking from hpp-core to Pinocchio, as this feature seems interesting for many applications, beyond hpp.

**Comment by dBierni** [comment]
The use of `hpp-core` is associated with the `hpp::pinocchio::Device`, so would be good for new applications. - If I correctly understand.

In my case whole system is created(the software is about motion planning for robotic arms), the only thing we want is to change the collision library. 

For now, I see an advantage to use `hpp::fcl`, so I will add the `BroadPhaseManager`. I am curious why did you delete the managers from `hpp::fcl`?

**Comment by florent-lamiraux** [comment]
>  I am curious why did you delete the managers from `hpp::fcl`?
In a robotics application, objects are moved by a kinematic chain. The collision between those objects should therefore be handled by classes aware of this data-structure. In our architecture, kinematic chains are handled outside `hpp-fcl`.

**Comment by jmirabel** [comment]
> In my case whole system is created(the software is about motion planning for robotic arms), the only thing we want is to change the collision library.

If your motion planning library does not handle collision pairs, then, yes, you must have a vector of collision pairs. If you do this, you may use class `ComputeCollision` https://gepettoweb.laas.fr/doc/humanoid-path-planner/hpp-fcl/master/doxygen-html/classhpp_1_1fcl_1_1ComputeCollision.html (useful for shape-shape requests).

**Comment by jcarpent** [comment]
> f your motion planning library does not handle collision pairs, then, yes, you must have a vector of collision pairs. If you do this, you may use class `ComputeCollision` https://gepettoweb.laas.fr/doc/humanoid-path-planner/hpp-fcl/master/doxygen-html/classhpp_1_1fcl_1_1ComputeCollision.html (useful for shape-shape requests).

Following @jmirabel remarks, Pinocchio does it in addition to handling the whole-kinematic chains ;)

**Comment by dBierni** [comment]
Thank you!

The collision-pairs are not the problem, this is something that is supported.  It was more about if there is something like `BroadPhaseManager` but is not something required.

`hpp::fcl` is already integrated into my system. The results of the tests are promising, still need to provide more but for now, it gives satisfactory results.
