### ISSUE TITLE
Moving to `std::shared_ptr`

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-fcl#218]
Hi,

The HPP framework is now using C++11, and is therefore going move to `std::shared_ptr` instead of `boost`ones.

Keeping `boost::shared_ptr` in hpp-fcl would be a pain, and this might not be totally necessary.

I suggest to move hpp-fcl to C++11 and `std::shared_ptr`, and to release a new major version for this change.

For pinocchio, and other third-parties that rely on hpp-fcl, this might lead to something like:
https://github.com/stack-of-tasks/pinocchio/blob/master/src/CMakeLists.txt#L51-L54

Obviously, I can handle this work, and the related updates in the HPP, SoT, loco-3d & gepetto projects, but **is there any objection for this** ?

My main motivation is that the current version of hpp-pinocchio is not compatible with pinocchio v2.6.0, so I can't publish pinocchio v2.6.0 on robotpkg until a new HPP release is done, and the switch to std::shared_ptr is already on-going on this new HPP release.

**Comment by jcarpent** [comment]
Why do say that hpp-fcl is C++11? This is not the case on my side.
I don't think that we need to go towards std::shared_ptr yet. For hpp-fcl 2.0, we already discussed a bit with @jmirabel on some improvements which may simplify hpp-fcl while also improving the whole performances.

**Comment by jcarpent** [comment]
> hpp-pinocchio is not compatible with pinocchio v2.6.0, so I can't publish pinocchio v2.6.0

What do you mean exactly?

**Comment by nim65s** [comment]
hpp-fcl is not yet C++11 only. 

In this issue, I am suggesting to change this, because this would be easier to switch all HPP at once, instead of having boost::shared_ptr in "hpp-fcl" and std::shared_ptr in "all HPP but hpp-fcl".

This would require less work to get everything working again, and will be faster.

And anyway, I guess we'll want to switch to `std::shared_ptr` in hpp-fcl at some point. C++11 is 10 years old now. So from my point of view, the question is "What are we waiting for", given that waiting more would require more work.

For hpp-pinocchio, cf. https://github.com/humanoid-path-planner/hpp-pinocchio/issues/146

**Comment by jcarpent** [comment]
For me, this will break compatibility with Pinocchio, because hpp-fcl objects are exposed in the current API of Pinocchio.
The only solution on my side will be to wait for Pinocchio 3.x which will make C++11 the default C++ version with template generation support.

My veto is to wait for Pinocchio 3.x. We can discuss in private to see what is missing to launch Pinocchio 3.x

**Comment by nim65s** [comment]
ok, let's synchronize with Pinocchio 3 then.

**Comment by jcarpent** [comment]
Thanks @nim65s for your compliance.

**Comment by jmirabel** [comment]
#256 raised the C++ 11 question again. It has been 9 months since this discussion was started. A few questions:
- What prevents future 2.x release of pinocchio to be C++ 11 ?
- Anyone else has an opinion on this ?

**Comment by jmirabel** [comment]
Is there any technical point that for keeping c++98 for new 2.x versions ?

This reason has frozen this discussion for 9 months and there is no clear
timeline for pinocchio 3 release. I am not putting pressure on pinocchio 3.
I just think that, if there is no technical reason to keep the 98
compatibility, then at some point we may decide to move forward anyway.

**Comment by jcarpent** [comment]
For, me the main reason is downstream users of Pinocchio which should stick to C++98. 
I don't want to abandon them at this stage and prefer to prepare the spirit with Pinocchio 3.x
This could be the same for hpp-fcl, with version 2.x and more, compliant with C++14 and more.

**Comment by jcarpent** [comment]
@nim65s You can now move on to this issue. #260 forces the switch to C++ 11 and more.
