### ISSUE TITLE
C++17 vs register keyword

### ISSUE THREAD

**Issue by wxmerkt** [humanoid-path-planner/hpp-fcl#220]
hpp-fcl currently does not build in workspaces that are set to use `CMAKE_CXX_STANDARD=17` since the `register` keyword is no longer supported. It is e.g. used here:
https://github.com/humanoid-path-planner/hpp-fcl/blob/40c9869a9f9a899afd1512ed4c1fca7cef322a42/src/BV/OBB.cpp#L166

To fix it, we could either (a) fix the code or (b) check that if a standard >14 is requested raise a CMake warning and force a maximum of C++14 for the project. 

What are your thoughts on removing the `register` keyword? Would you consider a PR for that?

**Comment by nim65s** [comment]
I think we should remove the `register` keyword, and check some benchmarks to ensure that we don't reduce performances doing so.

**Comment by jcarpent** [comment]
We can guess that modern compilers are smart enough to know what to do with this keyword. So indeed, we may remove it or just replace them with a macro only activated for old C++ versions.

**Comment by jcarpent** [comment]
I would go for the first option ;)
