### ISSUE TITLE
Invalid distance_lower_bound

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#227]
For simple geometries, like Box and Sphere collision pairs, the distance_lower_bound is not updated even when there is a contact.

**Comment by jmirabel** [comment]
For primitive shapes, the distance lower bound should be the real distance. I'm surprised it is not updated.

When this happens, can you check the distance request works correctly ? Maybe the issue comes from here.

**Comment by jcarpent** [comment]
Solved by #228.
