### ISSUE TITLE
Advice on how to use the Python bindings

### ISSUE THREAD

**Issue by Moult** [humanoid-path-planner/hpp-fcl#235]
G'day all! I'm building a open source library which previously used fcl, but due to the lack of well-distributed builds for python-fcl, I've recently discovered hpp-fcl and I'm investigating how to migrate. The library I'm building does collision detection for the architecture, engineering, and construction industry - basically checking whether static 3D objects intersect with each other. I'm really happy to see what looks like a vibrant and maintained fork!

A few questions:

 1. The Python bindings on Conda (https://anaconda.org/conda-forge/hpp-fcl/files) seem to depend on assimp. libassimp.so.5 is 240MB. This is quite large. Can this dependency be made optional? I'm not sure what it is needed for. I haven't needed it in the past with python-fcl.
 2. I'm looking for the equivalent functions to migrate my Python calls from fcl to hppfcl. Here's a list of functions that I use, as well as what I've mapped so far. Some, I'm uncertain about, and others I have no idea. I hope you can help :)

```
 - fcl.BVHModel --> hppfcl.BVHModelOBB
 - fcl.BVHModel.addSubModel --> hppfcl.BVHModelOBB.addSubModel
 - fcl.BVHModel.beginModel --> hppfcl.BVHModelOBB.beginmodel
 - fcl.BVHModel.endModel --> hppfcl.BVHModelOBB.endModel
 - fcl.CollisionData --> ?
 - fcl.CollisionObject --> hppfcl.CollisionObject
 - fcl.CollisionRequest --> hppfcl.CollisionRequest
 - fcl.Contact --> hppfcl.Contact
 - fcl.DistanceData --> ?
 - fcl.DistanceRequest --> hppfcl.DistanceRequest
 - fcl.DistanceResult --> hppfcl.DistanceRequest
 - fcl.DynamicAABBTreeCollisionManager --> ?
 - fcl.DynamicAABBTreeCollisionManager._extract_name --> ?
 - fcl.DynamicAABBTreeCollisionManager.add_object --> ?
 - fcl.DynamicAABBTreeCollisionManager.collide --> ?
 - fcl.DynamicAABBTreeCollisionManager.distance --> ?
 - fcl.DynamicAABBTreeCollisionManager.registerObject --> ?
 - fcl.DynamicAABBTreeCollisionManager.setup --> ?
 - fcl.DynamicAABBTreeCollisionManager.unregisterObject --> ?
 - fcl.DynamicAABBTreeCollisionManager.update --> ?
 - fcl.Transform --> hppfcl.Transform3f
 - fcl.defaultCollisionCallback --> ?
 - fcl.defaultDistanceCallback --> ?
```

Thanks so much :)

**Comment by jcarpent** [comment]
>     1. The Python bindings on Conda (https://anaconda.org/conda-forge/hpp-fcl/files) seem to depend on assimp. libassimp.so.5 is 240MB. This is quite large. Can this dependency be made optional? I'm not sure what it is needed for. I haven't needed it in the past with python-fcl.

assimp allows the loading of meshes described with various file formats. This is a very essential features for our software, so it won't be possible to deliver HPP-FCL without it. Yet, the depency can be made optional, but you will be in charge of providing maintening in conda. Is it fine for you?

**Comment by Moult** [comment]
@jcarpent if I am capable of maintaining it, I would be more than happy to if someone helped guide me in the beginning. What work would it involve? Does it require dedicated Mac hardware for macos builds?

**Comment by jcarpent** [comment]
>     2\. I'm looking for the equivalent functions to migrate my Python calls from fcl to hppfcl. Here's a list of functions that I use, as well as what I've mapped so far. Some, I'm uncertain about, and others I have no idea. I hope you can help :)

Some parts of the original FCL has been removed in HPP-FCL to ease the maintenance. Yet, with @jmirabel we realised that some broad-phase approach need to be reintegrated within HPP-FCL for external usages. This is in the roadmap but currently, we only have limited time to work on it. 
@Moult @Jesusbill Would be interested to provide some help on this task?

**Comment by Moult** [comment]
@jcarpent yes, very happy to help with it, with the only problem that I don't know anything about C++ or how these wrappers and build systems work (I don't have experience with compiled languages - only interpreted ones), but with a bit of guidance, I am able to learn what is necessary. I think there are others in our community who can help chip in as well. Potentially ping @brunopostle / @aothms .

**Comment by jmirabel** [comment]
I confirm that the collision manager should be reintroduced. At the moment, they are not here and so it is for the callbacks.

**Comment by nim65s** [comment]
@Moult : on Linux, if you install hpp-fcl with pip, you’ll get a 7.3M libassimp.so. The version provided by ubuntu is 7.8M. 

I don't see why it would be 240M.

Shouldn't we look at this issue, before trying to make it optional here ?

**Comment by jmirabel** [comment]
You may have installed a debug version.

**Comment by jcarpent** [comment]
@Moult to see how we can collaborate on this task with you and your colleagues, could you contact us (@jcarpent and @jmirabel ) by email to plan a common meeting?

**Comment by jmirabel** [comment]
Eventually, we may discuss on https://matrix.to/#/!RIQMdAhpDmKfuQYiYl:laas.fr?via=matrix.org

**Comment by Moult** [comment]
@nim65s I'm grabbing a build from Conda's repos, so that I can provide a build for Win, Mac, and Linux all from the same source. I'm not sure why Conda's build is so large.

Sorry for the late reply. I will lurk on Matrix to see when we can meet up for a chat :) I'm in the Sydney, Australia timezone. I've sent @jcarpent an email, but I don't know @jmirabel 's email.

**Comment by jcarpent** [comment]
I will close the issue as this discussion now occurs here: https://matrix.to/#/!RIQMdAhpDmKfuQYiYl:laas.fr?via=matrix.org

**Comment by jcarpent** [comment]
>     1. The Python bindings on Conda (https://anaconda.org/conda-forge/hpp-fcl/files) seem to depend on assimp. libassimp.so.5 is 240MB.

The issue has been solved here: https://github.com/conda-forge/assimp-feedstaock/pull/20
Thanks to @traversaro for his help on this.

**Comment by Moult** [comment]
Thank you so much for the quick fixes!
