### ISSUE TITLE
[package.xml] Dependency to eigenpy

### ISSUE THREAD

**Issue by olivier-stasse** [humanoid-path-planner/hpp-fcl#252]
As far I understood CMakeLists.txt the BUILD_PYTHON_INTERFACE is ON by default which is a dependency to eigenpy.
Is it ok if we reflect this dependency in the file package.xml ?

**Comment by jcarpent** [comment]
Totally fine on my side.

**Comment by florent-lamiraux** [comment]
I think it would be better to have two versions of the `package.xml`: one with dependency to eigen and one without and to install the right one depending on the value of variable `BUILD_PYTHON_INTERFACE`.

**Comment by jmirabel** [comment]
Having two package.xml will be very tedious to support. It is not only used for installing stuff but also for compiling when inside a catkin env.

`package.xml` isn't meant to support optional dependency. I think make it follow the default is best.

**Comment by wxmerkt** [comment]
As Joseph said, `package.xml` is meant to define the dependencies to be installed and compiled for the default setting. 

The current `package.xml` already contains the `eigenpy` depend-key (https://github.com/humanoid-path-planner/hpp-fcl/blob/304b088be931ac30fbdddf63031bc5b419d7c367/package.xml#L30), so I will close this issue. Please reopen @olivier-stasse if there's an issue I have missed?

**Comment by olivier-stasse** [comment]
No @wxmerkt My apologies ! Sorry for the noise ! 
I should have been more careful while reading the file...
