### ISSUE TITLE
BVH Model, issue with triangulated mesh

### ISSUE THREAD

**Issue by GianniLunardi** [humanoid-path-planner/hpp-fcl#257]
Hi, 

I found an issue related to the BVH Model OBBRSS class. I tried to compute the distance between a point and a surface given by a triangulated mesh. In the screenshot, the point is represented by the green sphere, the upper red surface is the mesh, while the blue sphere is the nearest point of the mesh with respect to the green point. It is possible to notice that the nearest point given by the algorithm is wrong (the blue dot is supposed to be under the green one). If I repeat the distance computations between two primitives (green sphere and the lower yellow plane), the results are correct, where the nearest point is the purple one, along the normal of the plane.

In the zip there are the screenshots that show the problem, a simple code as example and the obj file that contains the mesh. I do not know if the problem can be related to the mesh, maybe the BVH creates a volume when I want a surface as collision object.

Best regards,
Gianni Lunardi
[issue.zip](https://github.com/humanoid-path-planner/hpp-fcl/files/7971172/issue.zip)
![screen1](https://user-images.githubusercontent.com/60383150/151805293-fadf33f7-e059-41cd-9ea4-adf4d64a030f.png)

**Comment by florent-lamiraux** [comment]
It seems to me that the rotation defined in `example.py` line 38 is not the same as the one defined line 49. Could you rewrite your example by defining each rotation only once and then by using conversion functions?

**Comment by GianniLunardi** [comment]
There are wrong signs on the rotation matrix. Sorry for that, it was my fault. Thank you for the answer.
