### ISSUE TITLE
Hidden virtual in Python bindings overload for `distance`

### ISSUE THREAD

**Issue by wxmerkt** [humanoid-path-planner/hpp-fcl#267]
This warning appears to indicate an issue: The current Python API omits the third (out) parameter, the distance. Hence, the overload of `distance` doesn't actually return the distance:
```
In file included from /git/hpp-fcl/python/broadphase/broadphase.cc:58:
/git/hpp-fcl/python/broadphase/broadphase_callbacks.hh:82:8: warning: 'hpp::fcl::DistanceCallBackBaseWrapper::distance' hides overloaded virtual function [-Woverloaded-virtual]
  bool distance(CollisionObject* o1, CollisionObject* o2) { return this->get_override("distance")(o1,o2); }
       ^
/git/hpp-fcl/include/hpp/fcl/broadphase/broadphase_callbacks.h:80:16: note: hidden overloaded virtual function 'hpp::fcl::DistanceCallBackBase::distance' declared here: different number of parameters (3 vs 2)
  virtual bool distance(CollisionObject* o1, CollisionObject* o2, FCL_REAL & dist) = 0;
               ^
1 warning generated.
```

I might misinterpret the intent here - this doesn't appear to return the distance at all. To fix this, would a change of the Python API to `double distance(o1, o2)` be appropriate? Or should we add the `FCL_REAL& dist` as a parameter to fix it? Any other suggestions?

**Comment by jcarpent** [comment]
This is still a work in progress. Please be patient.

**Comment by jcarpent** [comment]
Thanks @wxmerkt for reminding me of this issue. We should keep the inout argument solution as the distance is updated.
The solution would consist in implementing the two signatures.
