### ISSUE TITLE
Is there an Anaconda package for Python 3.10?

### ISSUE THREAD

**Issue by Moult** [humanoid-path-planner/hpp-fcl#272]
G'day all! I'm looking at https://anaconda.org/conda-forge/hpp-fcl/files and can only find versions up to Python 3.9. I'm running hpp-fcl on Blender, which now Blender 3.1 uses Python 3.10. Is it possible to get a build for Python 3.10?

**Comment by traversaro** [comment]
The PR for adding 3.10 conda packages still needs to be merged: https://github.com/conda-forge/hpp-fcl-feedstock/pull/57 .

**Comment by Moult** [comment]
@traversaro awesome! I'll keep an eye out for its merging then :)

**Comment by jcarpent** [comment]
Merged. Thanks @traversaro and @Moult
