### ISSUE TITLE
Formatting commits via pre-commit

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#279]
@nim65s, @florent-lamiraux, @jmirabel 

With @nim65s, we have been discussing using pre-commit to force the formatting of the projects.
This will enable to have the same standard to apply to everybody.

I will open a PR in this direction, and the rules should be effective for hpp-fcl 2.0
Is it fine for everybody?

**Comment by jmirabel** [comment]
You mean applying clang format before committing. Does it mean you have to have clang format to be able to commit ?
Do you plan to apply code formatting to the whole repo ?

**Comment by jcarpent** [comment]
> Does it mean you have to have clang format to be able to commit ?

You will be able to configure the commit formatting via `pre-commit install`.
A bot will check if the commits comply with the internal project rules.

> Do you plan to apply code formatting to the whole repo ?

I would say yes. With a single commit line.

**Comment by nim65s** [comment]
> You mean applying clang format before committing. 

For people who run `pre-commit install`, yes.

> Does it mean you have to have clang format to be able to commit ?

No. If you use `pre-commit install`, pre-commit will install clang-format in a venv made for pre-commit.

And if somebody doesn't have `pre-commit`, or doesn't run `pre-commit install`, it's not an issue: pre-commit CI will add formatting commits in every PR from that person.

> Do you plan to apply code formatting to the whole repo ?

It would be better

**Comment by florent-lamiraux** [comment]
If it is automatic, I agree.

**Comment by jcarpent** [comment]
Solved with #280.
