### ISSUE TITLE
Ellipsoid not available in python bindings

### ISSUE THREAD

**Issue by EpicDuckPotato** [humanoid-path-planner/hpp-fcl#285]
It looks like hppfcl has an Ellipsoid class: https://gepettoweb.laas.fr/doc/humanoid-path-planner/hpp-fcl/devel/doxygen-html/classhpp_1_1fcl_1_1Ellipsoid.html. Is it possible to use this in python? I tried

`import hppfcl`
`print(hppfcl.Ellipsoid)`

and got the error
`AttributeError: module 'hppfcl' has no attribute 'Ellipsoid'`

**Comment by jmirabel** [comment]
It is available. You probably have to update your installation.
https://github.com/humanoid-path-planner/hpp-fcl/blob/70c5ff842fc7364e2fd357048e00f60ab40475a2/python/collision-geometries.cc#L322

**Comment by EpicDuckPotato** [comment]
Do you know when I'd be able to get this update on robotpkg? From what I understand, the latest version including ellipsoids is not on robotpkg, so I can't install with apt. I have an existing setup with pinocchio, crocoddyl, and hppfcl using apt that I'm hoping to stick with.

**Comment by nim65s** [comment]
Probably in a couple of days

**Comment by EpicDuckPotato** [comment]
sweet, thanks!
