### ISSUE TITLE
Projection onto simplex in GJK

### ISSUE THREAD

**Issue by lmontaut** [humanoid-path-planner/hpp-fcl#291]
Hi @jmirabel,

I was wondering why 2 different kinds of functions exist in hppfcl to project a point onto a simplex, i.e a tetrahedron (same question for triangle and line):
- The solver `GJK` (in `narrowphase/gjk.h`) uses `GJK::projectTetrahedraOrigin`.
- To recover the weights of the convex combination of the solution found by GJK, `Project::projectTetrahedra` is used. This function is identical to the function used by FCL inside GJK but is significantly shorter and simpler to understand than `GJK::projectTetrahedraOrigin`.

Is it because one is faster than the other?
Thanks!

**Comment by jmirabel** [comment]
Hi,

If I remember correctly, `GJK::project...Origin` can only be called under certain conditions (which are valid when called from GJK). In these circumstances, some case need not to be checked. See https://caseymuratori.com/blog_0003 for more information.

I am almost sure the member function in `GJK` are significantly faster. At least, they were designed to be faster.

**Comment by jmirabel** [comment]
If needed, we can discuss orally.

**Comment by lmontaut** [comment]
Ok I think I understand better now, thanks @jmirabel. :) 
The projection used in `GJK::project...Origin` is described in [Ericson's book](https://realtimecollisiondetection.net/) page 403. It uses voronoi regions and caches computations so the projections are very efficient, contrary to `project...` which checks each feature of the simplex and tracks a minimum distance.

However, it seems Ericson never mentions that these projections are specific to simplexes constructed by GJK. Actually he says that the simplex projections used in GJK are the same as the projections he describes in chapter 5 of his book, which can be used for arbitrary simplex.

**Comment by lmontaut** [comment]
Ok, looking at what you pointed at @jmirabel , [https://caseymuratori.com/blog_0003](https://caseymuratori.com/blog_0003), it seems that indeed we can only call `GJK::project...Origin` from GJK because even more checks are added on top of what Ericson describes; these use the order of construction of the simplex.

I think it's a good idea to have Ericson's book in addition to [https://caseymuratori.com/blog_0003](https://caseymuratori.com/blog_0003), as the voronoi thing is described by Ericson in one page and is easy to understand.

**Comment by jcarpent** [comment]
#296 provides internal doc.
