### ISSUE TITLE
Loading meshes with python bindings

### ISSUE THREAD

**Issue by kingjin94** [humanoid-path-planner/hpp-fcl#292]
Rather recently (within the last few weeks) there seems to have been a shift in the implementation of hpp-fcl's python bindings build for conda (version 1.8.1; here installed as a dependency of pinocchio==2.6.4). This leads to mangled stl imports via the MeshLoader. A closer analysis showed that it seems to transpose the vertex matrix somehow (kind of loading column first instead of row first):

Instead of vertices = [ [v1_x v1_y v1_z] [v2_x v2_y v2_z] ... [vN_x vN_y vN_z] ] one gets [ [v1_x vN/3 v2N/3] [v1_y ... ] [v1_z ...] ].

Steps to reproduce:

(from a clean environment, e.g., docker run -ti -v <someDemoSTL> continuumio/miniconda3 /bin/bash)
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install hpp-fcl==1.8.1

In python:

import hppfcl
mesh_loader = hppfcl.MeshLoader()
m = mesh_loader.load(<anySTLFile>) # with known coordinates
m.vertices()  # Broken
m.vertices().T.flatten().reshape((-1,3)) # atleast first one third of table ok; there seems to be a offset ignored for the rest of the stl file

**Comment by jmirabel** [comment]
Hi,

It is unlikely there is a bug here since this is used in so many cases in different environments.

I haven't thought it thoroughly but I suspect the args of `reshape` should be `(3, -1)` instead.

**Comment by jcarpent** [comment]
We have fixed a bug the last week-end in EigenPy about RowMajor matrices parsing. Could you restart from a fresh conda and check that eigenpy (`conda list`) is at version heeeb17e_0?

**Comment by jcarpent** [comment]
This should work. At least it works perfectly on my side with file attached to the comment.
I obtain:
```
In [5]: m.vertices()
Out[5]: 
array([[-35.,  60.,  20.],
       [-55.,  60.,  20.],
       [-35.,  40.,  20.],
       [-55.,  40.,  20.],
       [-35.,  40.,   0.],
       [-55.,  40.,   0.],
       [-35.,  60.,   0.],
       [-55.,  60.,   0.]])
``
[cube.stl.zip](https://github.com/humanoid-path-planner/hpp-fcl/files/8652550/cube.stl.zip)
`

**Comment by kingjin94** [comment]
> We have fixed a bug the last week-end in EigenPy about RowMajor matrices parsing. Could you restart from a fresh conda and check that eigenpy (`conda list`) is at version heeeb17e_0?

That fits my observation that a clean install resolved the issue. Thank you for pointing out that their have been some alterations recently.
