### ISSUE TITLE
Collision between boxes and ellipsoids

### ISSUE THREAD

**Issue by EpicDuckPotato** [humanoid-path-planner/hpp-fcl#293]
I installed the latest hppfcl version from source, but it looks like collisions between ellipsoids and boxes are not yet supported, as I got this error:

`message: Collision function between node type GEOM_BOX and node type GEOM_ELLIPSOID is not yet supported`

When might this become available?

**Comment by jcarpent** [comment]
This is a mistake from our side. @lmontaut will add it very soon. Sorry for the noise.

**Comment by EpicDuckPotato** [comment]
Cool, thanks!
