### ISSUE TITLE
Discrepancy btw GJK+EPA and specialized functions regarding witness points

### ISSUE THREAD

**Issue by lmontaut** [humanoid-path-planner/hpp-fcl#307]
Hi,
I have the following script which computes the distance between a sphere and a box:
```
import hppfcl
import numpy as np

r = 0.5
o1 = hppfcl.Sphere(r)
# o1 = hppfcl.Ellipsoid(r, r, r)
T1 = hppfcl.Transform3f(np.eye(3), np.array([0, 0, r]))

rbox = 2 * r
o2 = hppfcl.Box(rbox, rbox, rbox)
T2 = hppfcl.Transform3f(np.eye(3), np.zeros(3))

request = hppfcl.DistanceRequest()
result = hppfcl.DistanceResult()
dist = hppfcl.distance(o1, T1, o2, T2, request, result)
print(f"Distance = {dist}")
print(f"Normal = {result.normal}")
print(f"p1 = {result.getNearestPoint1()}")
print(f"p2 = {result.getNearestPoint2()}")
```
which outputs:
```
Distance = -0.5
Normal = [-0. -0. -1.]
p1 = [0.  0.  0.5]
p2 = [0.  0.  0.5]
```
Under the hood, `hppfcl.distance(...)` is using the **specialized function** `sphereSphereDistance(...)`.

If I now replace `o1 = hppfcl.Sphere(r)` with `o1 = hppfcl.Ellipsoid(r, r, r)`, `hppfcl.distance(...)` is now using **GJK+EPA**.
I get the following output:
```
Distance = -0.4999999999989329
Normal = [-1.16274225e-11  1.18861597e-11 -1.00000000e+00]
p1 = [ 5.43733207e-07 -4.25368667e-07  1.06714637e-12]
p2 = [ 5.43739021e-07 -4.25374610e-07  5.00000000e-01]
```
I essentially get the same result *except* for the position of the witness points `p1` and `p2`. This example illustrates the fact that there seems to be a discrepancy between how the specialized collision/distance functions and GJK+EPA view the nearest points when there is a collision. It seems that most specialized functions (located in `narrowphase/detail.h`) see the nearest points as sharing the same position, whereas GJK+EPA returns the witness points which correspond to the separation vector.

Is this intentional? In my opinion, the output of GJK+EPA is the correct one as the points it outputs are where contact forces would be applied on each shape.

**Comment by jmirabel** [comment]
Originally, the notion of contact point was very fuzzy in FCL. I think it is any point in the intersection.

By definition, shouldn't GJK+EPA return points on the surface since they are points built by the support function ?
The points you show seems more like a bug in EPA to me. I haven't checked the code so I may be wrong.

It is not easy (and probably physically meaningless) to relate contact points and contact forces. I think you should reformulate your question in terms of what a simulator needs in order to be as close to the real world physics.

FWIW since I haven't implemented a simulator, my answer to this is: Ideally, the simulator would locate a) the time of impact and b) the impact point at that time. This may be a bit slow though.

**Comment by jmirabel** [comment]
After double thinking about that, I think there is a bug. In the Ellipsoid vs Box case, p1 is more or less zero, which isn't on the ellipsoid, and `p = p1 - p2` isn't a separation vector. You need `2*p`.

I think the meaning `p1` and `p2` is as follow. They are points in `object1` and `object2` frames respectively. They are the same point in the global frame. I.e. `tf1.transform(p1) == tf2.transform(p2)`. So GJK+EPA is not correct.

If you need two points that make the separation vector, I would suggest to add a new field.

**Comment by jcarpent** [comment]
With respect to my previous remark, I think we should not change p1 and p2 from GJK+EPA, but rather modifying the remaining methods.
Indeed, the definition of the contact points is very specific to the contact model in use and having collocated points is not the best IMHO.

**Comment by jcarpent** [comment]
@jmirabel We can discuss orally the three of us to better converge towards a consensus.

**Comment by lmontaut** [comment]
@jmirabel I think GJK+EPA is defining well `p1` and `p2`. In the code (method `shapeDistance` in file `narrowphase.h`  we have:
```
p1 = tf1.transform(w0);
p2 = tf1.transform(w1);
```
where `w0` and `w1` come from GJK+EPA and are defined in the frame of `o1`. To put them in the world frame, we apply the transformation `tf1`.

Regarding the example I put above, we have the following figure:
![witness-points](https://user-images.githubusercontent.com/27144054/175093004-366f530c-f9a1-4fed-a553-b883ea878e63.png)
and the vector `p1-p2` corresponds to the separation vector.

**Comment by jmirabel** [comment]
I understand why it's interesting to have the definition you say and I'm fine adding it. I am only annoyed by:
- the change in meaning, that may silently break user's code,
- the fact that BVH will not follow that convention either, while, up to now, except for GJK, I think all pairs uses the old convention.

My point on this is to add something without removing what's already there.

If we want to remove the old attributes later, we can make it deprecated so that user can update their code following a compilation warning. And we still have the old attributes which we can make homogeneous between pairs.

**Comment by lmontaut** [comment]
Hi @alaurenzi, thanks for your interest in hppfcl! Yes you are correct. The output between GJK+EPA and specialized functions should be the same when calling the `distance(...)` function. At the moment, this is the case for most functions, but as you pointed out `sphere-capsule` is wrong.
This is because certain `distance` functions actually use their `collide` counterparts.
However, there is a discrepancy however in how `distance` and `collide` behave:
- `collide` populates `CollisionResult` with a contact point and a signed distance.
- `distance` populates `DistanceResult` with a two witness points and a signed distance.

There is a one to one relationship between the contact point `p` and the witness points `p1` and `p2` as `p = 0.5 * (p1 + p2)` and `signed_distance = +/- ||p1 - p2||`, but it's annoying that `distance` behaves differently depending on wether or not it calls `collide` in the background.

@jmirabel @jcarpent I think that if we do the following, we will fix the problems mentioned above. It may break users' code but will make things much clearer:
- Make the computation of `p1` and `p2` the same when `distance` is called, that means making everything behave like GJK+EPA. At the moment, only a few functions do not behave like GJK+EPA (`sphere-capsule, sphere-sphere, sphere-cylinder`)
- add a `contact_point` field in `DistanceResult` like in `CollisionResult` such that `contact_point = 0.5 * (p1 + p2)`. 
- add a `nearest_points` fields in `CollisionResult` like in `DistanceResult` that would only be populated when the shapes are in collision.

**Comment by florent-lamiraux** [comment]
Hello @lmontaut,
If you add some fields in `CollisionResult` and `DistanceResult`, and do not change the result of the existing fields, why would it break user's code ?
At some point, we also might merge these two classes into one.

**Comment by lmontaut** [comment]
Hi @florent-lamiraux! At the moment, if `distance` is used to compute the nearest points between `sphere-sphere`, it will return collocated points. However, for a majority of other collision pairs, `distance` will return separated points like in the drawing above.
The change I propose would make `sphere-sphere` (and `sphere-capsule` etc.) behave like every other collision pair. So it's not "breaking" the code, but if someone was using hppfcl for computing `distance` on `sphere-whatever` and was used to having collocated nearest points, this would change.
But having collision pairs that behave the same way is more important I would say.

I agree on the merge, we just have to be careful about the fact that `CollisionResult` and `DistanceResult`behave differently when the shapes are not intersecting:
- `CollisionResult` returns an estimate of the distance
- `CollisionResult` returns no contact/witness points when `DistanceResult` does
(This is due to GJK being early-stopped when `collide` is called)

**Comment by jmirabel** [comment]
@lmontaut I'm fine with modifying the attributes. What you propose goes into the direction of merging collision and distance result into one class. This makes complete sense when considering that computing the distance should be equivalent (in theory although not true in practice) to collision with an infinite break distance.

**Comment by lmontaut** [comment]
@jmirabel I agree merging the two would be a good idea. I will do a first PR to uniformize the behaviors discussed above and in a furture PR we can deprecate both `CollisionResult` and `DistanceResult` to have everything in `QueryResult`.

**Comment by jcarpent** [comment]
This notably implies that we are breaking the API ...

**Comment by jcarpent** [comment]
Solved in hppfcl3x
