### ISSUE TITLE
Benchmark compared to FCL or Bullet

### ISSUE THREAD

**Issue by olivierp99** [humanoid-path-planner/hpp-fcl#313]
Hello,

I was wondering what was the speed up of this library compared to the original FCL library or even compared to bullet.
Edit: For convex shapes or bvh or both

Cheers

Olivier

**Comment by jcarpent** [comment]
@lmontaut Do you think you can create such a benchmark?
@olivierp99 I would say that the main objective of FCL and hpp-fcl is modularity, contrary to Bullet. Depending on your needs, you should take this fact into account. One of the main advantage of hpp-fcl compared to FCL itself is the reduced number of bugs which have been fixed in hpp-fcl, mostly by @jmirabel and @florent-lamiraux.

**Comment by olivierp99** [comment]
Hello again and thanks a lot for all of your answers! I am currently using FCL and it's been working fine. I was maybe looking to switch as it's not really maintained anymore and wondered what was the speed up as the same time.
Feel free to close the issue
Have a nice day!

**Comment by jmirabel** [comment]
> @jmirabel @jcarpent I compared hppfcl and CCD for collision detection. I took meshes from the shapenet dataset and found that hppfcl was about 2x faster than CCD if I recall correctly. I can do the same kind of benchmark against FCL, bullet, with a more diverse set of shapes than just meshes.

FCL uses CCD so I guess FCL is slower than or equal to CCD as it has to convert the shapes and the results. I don't think it is necessary to compare FCL and hpp-fcl for convex objects. It can make sense for BVH.

**Comment by jcarpent** [comment]
> FCL uses CCD so I guess FCL is slower than or equal to CCD as it has to convert the shapes and the results



> > @jmirabel @jcarpent I compared hppfcl and CCD for collision detection. I took meshes from the shapenet dataset and found that hppfcl was about 2x faster than CCD if I recall correctly. I can do the same kind of benchmark against FCL, bullet, with a more diverse set of shapes than just meshes.
> 
> FCL uses CCD so I guess FCL is slower than or equal to CCD as it has to convert the shapes and the results. I don't think it is necessary to compare FCL and hpp-fcl for convex objects. It can make sense for BVH.

CCD only requires support function, so there is no real need to convert objects.
Yet, @lmontaut has compared both (hpp-fcl and CCD) and hpp-fcl is much more faster, including the fact that we have recently accelerated the underlying GJK algorithm (see https://hal.archives-ouvertes.fr/hal-03662157/).

**Comment by jcarpent** [comment]
> Hello again and thanks a lot for all of your answers! I am currently using FCL and it's been working fine. I was maybe looking to switch as it's not really maintained anymore and wondered what was the speed up as the same time. Feel free to close the issue Have a nice day!



> Hello again and thanks a lot for all of your answers! I am currently using FCL and it's been working fine. I was maybe looking to switch as it's not really maintained anymore and wondered what was the speed up as the same time. Feel free to close the issue Have a nice day!

The main gain would be at the bug fixes level to avoid indirect bugs and also better performances in general according to the whole discussion.

**Comment by jmirabel** [comment]
> CCD only requires support function, so there is no real need to convert objects.

I let you check FCL source code. The are conversions between FCL classes and CCD classes.

**Comment by jcarpent** [comment]
> I let you check FCL source code. The are conversions between FCL classes and CCD classes.

I certainly mismatched with the way @lmontaut used libccd to compare against hpp-fcl.
