### ISSUE TITLE
Use GitHub Actions to create wheels to install with pip

### ISSUE THREAD

**Issue by rayzchen** [humanoid-path-planner/hpp-fcl#317]
For non-conda users

**Comment by jcarpent** [comment]
You can already install hpp-fcl via pip (https://pypi.org/project/hpp-fcl/). I let @nim65s complement this answer.

**Comment by nim65s** [comment]
Creating wheels for C++ packages that have C++ dependencies not already on PyPI is challenging. 

We already have some working published at https://pypi.org/project/hpp-fcl/ as @jcarpent pointed, and you should already be able to use those, but their creation is tedious.

A work in progress to fix this is available at https://github.com/cmake-wheel and should be released by the end of the summer.

**Comment by nim65s** [comment]
Right, both work already published and in cmake-wheel are based on manylinux, so no OSX / Windows support for now. This will come after the summer :)

**Comment by nim65s** [comment]
> Is it possible to just directly create a wheel that bundles the built Python extensions as data files?

It is, but I don't see the point.

> On a side note, how do you build the Python package into a directory without copying it directly to Python’s site-packages?

CMake let us decide where we want to install the built stuff. But I probably don't understand your question.

**Comment by nim65s** [comment]
Metadata in wheels are in a `.dist-info/` folder, as specified by the spec: https://peps.python.org/pep-0427/#the-dist-info-directory
You can just download / unzip one and see.

**Comment by rayzchen** [comment]
I meant when the wheels are generated, with `python setup.py bdist_wheel` or something.

**Comment by jcarpent** [comment]
@rayzchen Why to not use conda directly?

**Comment by nim65s** [comment]
The wheels already on PyPI are generated with metadata from another package manager, robotpkg. You probably don't want to look into that for windows.
The metadata for the upcoming wheels is in pyproject.toml, as specified by https://peps.python.org/pep-0621/

**Comment by rayzchen** [comment]
> @rayzchen Why to not use conda directly?

I'm experimenting with the Windows embeddable package and wheels make things much easier. I also don't have any experience with Conda and I don't want to mix 3 installations of Python together.

**Comment by jcarpent** [comment]
On our side, from a deployment perspective, it appears that conda is the best tool, elegant, easy-to-use and highly efficient.
Unfortunately, you will have to wait for our automatic deployment system on pip to be released (which should take some time).
