### ISSUE TITLE
ROS packages for newer versions

### ISSUE THREAD

**Issue by tokoro10g** [humanoid-path-planner/hpp-fcl#323]
Hi! Are there any plans to publish ROS packages for version 2.0+?

**Comment by wxmerkt** [comment]
Hi @tokoro10g,
Yes there are. Initially we will release hpp-fcl v2 for ROS2. We subsequently plan to update ROS1 packages to hpp-fcl v2. Pinocchio is now compatible with both hpp-fcl v1 and hpp-fcl v2 so that should be fine.

For which version are you looking for a release?

**Comment by tokoro10g** [comment]
Thank you for the quick response!

> Yes there are. 

Good to hear that.
I am especially interested in the latest version with Nesterov acceleration. I look forward to seeing it released!

**Comment by wxmerkt** [comment]
In which ROS distributions are you primarily interested in?

**Comment by tokoro10g** [comment]
I am planning to use this package with ROS1 noetic.

**Comment by wxmerkt** [comment]
I've released HPP-FCL 2.1.2 for ROS, including Noetic. It will take until the next sync until they are available for all users. From later this week you can grab them from shadow/ros-testing

**Comment by tokoro10g** [comment]
@wxmerkt Thank you very much!
