### ISSUE TITLE
Remove EigenPy dependency

### ISSUE THREAD

**Issue by rayzchen** [humanoid-path-planner/hpp-fcl#328]
Is there a way to make the Python bindings not depend on NumPy by removing its dependency on eigenpy? As far as I can tell, eigenpy is only being used to input matrices and vectors to various functions, but couldn't lists work the same way? NumPy is not exactly lightweight. Or, there could be a compilation flag that switches between using eigenpy and conversion between Eigen matrices and vectors to Python lists, without using NumPy.

**Comment by jcarpent** [comment]
You mean you don't want to use NumPy, which is pretty much a standard, no?

**Comment by rayzchen** [comment]
Basically, yes.

**Comment by jcarpent** [comment]
This is unusual but seems possible. If you need it, I would let you do the job.
We don't have the bandwidth for that. Sorry.

**Comment by rayzchen** [comment]
I'm not too sure how the Python c-extension works, but I'd be glad to try and do it myself, given some time to understand how EigenPy works.

**Comment by nim65s** [comment]
do you mean to add the with/without numpy switch in eigenpy or in hpp-fcl ?

**Comment by jcarpent** [comment]
I let you navigate through EigenPy. It should be relatively easy to do.

**Comment by rayzchen** [comment]
In hpp-fcl

**Comment by nim65s** [comment]
Ok, then you just need to look at .cc files in the python/ dir.
This is not using python c-api directly, but boost::python.

you could stick to boost::python, or switch to a more lightweight/modern pybind11/nanobind, or go raw on the official python c-api.

**Comment by rayzchen** [comment]
I'm having trouble building hpp-fcl, I installed eigenpy using the steps on their GitHub but I get:
```
CMake Error at CMakeLists.txt:100 (FIND_PACKAGE):
  By not providing "Findeigenpy.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "eigenpy", but
  CMake did not find one.

  Could not find a package configuration file provided by "eigenpy"
  (requested version 2.2) with any of the following names:

    eigenpyConfig.cmake
    eigenpy-config.cmake

  Add the installation prefix of "eigenpy" to CMAKE_PREFIX_PATH or set
  "eigenpy_DIR" to a directory containing one of the above files.  If
  "eigenpy" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by nim65s** [comment]
you should have started there…

And this issue is already addressed in #327

**Comment by nim65s** [comment]
this error message is explicit: eigenpy is not installed in a place known to CMake. Did you run `make install` in eigenpy ? It should show the full installation paths of all files, including this `eigenpyConfig.cmake` hpp-fcl is complaining about.

Then put the prefix of this eigenpy install into your `CMAKE_PREFIX_PATH` environment variable.

**Comment by rayzchen** [comment]
I didn't build eigenpy locally, I installed it from the robotpkg source repo using `apt`.

**Comment by nim65s** [comment]
ok, then try this:
```
rm -rf build
export CMAKE_PREFIX_PATH=/opt/openrobots
mkdir build
cd build
cmake ..

**Comment by jcarpent** [comment]
> Ok, then you just need to look at .cc files in the python/ dir. This is not using python c-api directly, but boost::python.
> 
> you could stick to boost::python, or switch to a more lightweight/modern pybind11/nanobind, or go raw on the official python c-api.

Not really, the idea need to remove the dependency to NumPy, this is done by adding converters from Eigen objects to list of numbers.

**Comment by nim65s** [comment]
NB: eigenpy dependency is optional. you can already use `cmake -DBUILD_PYTHON_INTERFACE=OFF ..` if you don't want numpy / eigenpy ;)

**Comment by jcarpent** [comment]
@rayzchen is using Python.

**Comment by rayzchen** [comment]
What does `eigenpy::register_symbolic_link_to_registered_type` do?

**Comment by rayzchen** [comment]
How does EigenPy make it so that numpy arrays are automatically converted to Eigen vectors or matrices?

**Comment by jcarpent** [comment]
You should share your code instead ...

**Comment by rayzchen** [comment]
None of the listed files are modified.

**Comment by jcarpent** [comment]
I don't understand what you are currently doing. You are providing too little info.

**Comment by rayzchen** [comment]
I'm compiling hpp-fcl on Linux

**Comment by jcarpent** [comment]
Please provide le full log, including the cmake config. Hard to say anything otherwise.

**Comment by jcarpent** [comment]
By the way, we have never encountered this error while eigenpy operates on many OS (linux, BSD, OS X, Windows, etc.)

**Comment by rayzchen** [comment]
https://pastebin.com/NJtstsRL changes (or use https://github.com/rayzchen/hpp-fcl/tree/disable-eigenpy)
https://pastebin.com/CqbW0a6G cmake log

commands:
```
mkdir build
cd build
cmake .. -DEIGEN_DISABLED
make -j4
```

**Comment by rayzchen** [comment]
Same output on this dockerfile (use above patch)
https://pastebin.com/8gxTmi5a

**Comment by jcarpent** [comment]
Why `cmake .. -DEIGEN_DISABLED`?

**Comment by jcarpent** [comment]
You need Eigen in all cases.

**Comment by rayzchen** [comment]
whoops typo, should be `EIGENPY_DISABLED`

**Comment by jcarpent** [comment]
OK. I understand. For some function, we are using Eigen::MatrixBase that you cannot delete because the destructor is missing. In EigenPy, we carefully handle it. 

You need to do the same stuff as done in these files: https://github.com/stack-of-tasks/eigenpy/blob/master/include/eigenpy/eigen-to-python.hpp and https://github.com/stack-of-tasks/eigenpy/blob/master/include/eigenpy/eigen-from-python.hpp but changing the converter from or to Numpy objects.

**Comment by jcarpent** [comment]
@rayzchen Ane news on that issue?

**Comment by rayzchen** [comment]
Nope, I don't understand how those two files work, especially how to modify them to use Python lists instead of Numpy arrays. I also don't know how to make Python lists share the same memory.

**Comment by jcarpent** [comment]
This is not possible to share the memory with double elements in a list.

**Comment by jcarpent** [comment]
I think I will then close this issue as it seems to be stuck. I remain convinced that NumPy is a good choice, as it is well maintained and deployed.
In addition, it allows to easily share the memory between Python and C++.

**Comment by rayzchen** [comment]
I guess that seems reasonable. What functions and attributes does EigenPy use from NumPy? I was wondering if I could make a proxy module or a mockup of NumPy.
