### ISSUE TITLE
the lib hpp build from source is slower than the one install using apt install

### ISSUE THREAD

**Issue by mcaniot** [humanoid-path-planner/hpp-fcl#336]
Hi,

I have a weird issue. I work on a jetson so i need to compile from source due to the arm architecture. I install pinocchio and hpp-fcl from source and i have a huge difference when i'm loading the meshes for collsion computation using the lib install from source. I tried on my laptop a linux ubuntu 20.04 and the result are the same. When I used the libhpp.so from source i have a delay and i don't have one when i used the one provide by apt install. I also tried using the package [here](http://robotpkg.openrobots.org/distfiles/hpp-fcl-1.8.1.tar.gz) and the result is the same. Can you tell me why such a difference ?

**Comment by nim65s** [comment]
Hi,

Are all your projects compiled in Release mode ? hpp-fcl is super slow if you don't activate compiler optimisations.

**Comment by mcaniot** [comment]
Hi ! 
Thanks a lot you save my day. It was indeed the release mode that was missing in order to compile hpp.
