### ISSUE TITLE
More flexible CMake configuration

### ISSUE THREAD

**Issue by JeffHough** [humanoid-path-planner/hpp-fcl#338]
I had some trouble configuring the cmake for this project. Specifically, I'll list out a few problems I ran into that seem like they are potentially caused by how the `CMakeLists.txt` is written, but I am not 100% sure.

## Is it possible to _not_ build with octomap?

As seen in the cmake:

```
# Optional dependencies
ADD_PROJECT_DEPENDENCY(octomap PKG_CONFIG_REQUIRES "octomap >= 1.6")
if(octomap_FOUND)
  SET(HPP_FCL_HAS_OCTOMAP TRUE)
  string(REPLACE "." ";" VERSION_LIST ${octomap_VERSION})
  list(GET VERSION_LIST 0 OCTOMAP_MAJOR_VERSION)
  list(GET VERSION_LIST 1 OCTOMAP_MINOR_VERSION)
  list(GET VERSION_LIST 2 OCTOMAP_PATCH_VERSION)
  message(STATUS "FCL uses Octomap")
else()
  SET(HPP_FCL_HAS_OCTOMAP FALSE)
  message(STATUS "FCL does not use Octomap")
endif()
```

Which, it would appear, forces octomap to be included if it can be found. If octomap is an optional dependency, should it not be an `option`? Something like: 

```
option(HPP_FCL_USE_OCTOMAP "whether to use octomap" OFF)
# Optional dependencies
if (HPP_FCL_USE_OCTOMAP ON)
  ADD_PROJECT_DEPENDENCY(octomap PKG_CONFIG_REQUIRES "octomap >= 1.6")
  if(octomap_FOUND)
    SET(HPP_FCL_HAS_OCTOMAP TRUE)
    string(REPLACE "." ";" VERSION_LIST ${octomap_VERSION})
    list(GET VERSION_LIST 0 OCTOMAP_MAJOR_VERSION)
    list(GET VERSION_LIST 1 OCTOMAP_MINOR_VERSION)
    list(GET VERSION_LIST 2 OCTOMAP_PATCH_VERSION)
    message(STATUS "FCL uses Octomap")
  else()
    SET(HPP_FCL_HAS_OCTOMAP FALSE)
    message(STATUS "FCL does not use Octomap")
  endif()
endif()
```
That way, I could simultaneously have a system install of `octomap` and still choose not to use it?

Furthermore, I could not find any documentation on the cmake website for the function/macro `ADD_PROJECT_DEPENDENCY`, so I am not sure how it works. Is the "option" somehow built in to that?

## Is `assimp` a required dependency? Or is it meant to be optional?
The listed dependencies in the `INSTALL` file are:
```
Dependencies:
============

 - Eigen
 - Boost (thread, date_time, unit_test_framework, filesystem)
 - octomap (optional dependency, available at http://octomap.github.com)
 - Qhull (optional dependency, available at http://www.qhull.org)
```

So, `assimp` doesn't appear to be required.

Yet in the cmake file at line 155 there is this line: `FIND_PACKAGE(assimp REQUIRED)`. Is assimp a dependency then? Is it also meant to be optional? I'm not familiar with the library, so it isn't really clear to me why it would be needed.

## Always build shared libraries?

For my particular application, I would prefer static linking. But it would seem that the fcl target is hard-coded to be `SHARED`, rather than the usual method of picking either `STATIC` or `SHARED` based on a cmake `option` (for example, this option exists in the standard FCL library).

Is there a reason why this library cannot be linked statically?

Thanks for your help!!

**Comment by jcarpent** [comment]
@JeffHough Thanks for the report. Could you explain why you need only minimal dependency? Why to not install hpp-fcl from common package managers (apt, brew, conda, etc.)?

**Comment by nim65s** [comment]
For the first and third questions, yes, we can add options I think. Do you want to contribute this ?
For assimp, I think this is required, and the INSTALL file is obsolete. But I'm not sure, what exactly assimp is used for, I don't know if it is worth to try to find a way without it.

**Comment by jcarpent** [comment]
assimp allows the loading of meshes, so I would say this is required dependency to use advanced meshes.

**Comment by JeffHough** [comment]
Thank you both for your quick replies!

@jcarpent in my case, I'm working with a machine that uses a non-standard operating system, so using package managers isn't available. Instead what I have is a toolchain to cross-compile over to that machine, so I've been building everything from source. I don't neccesarily need minimal dependencies, but I am trying not to include things that I don't think will be used to keep the overall system as simple as possible.

@nim65s sure! I'd be happy to contribute something to the project.

**Comment by JeffHough** [comment]
I've now opened a PR to add some flags into the cmake.
