### ISSUE TITLE
Newbie guide? Sphere-cylinder collision check

### ISSUE THREAD

**Issue by kshfire** [humanoid-path-planner/hpp-fcl#339]
I'm a newbie of the HPP-FCL.
I wonder that is there recent (official) documents or tutorials how to use the hpp fcl ?

Actually, referring test files, I've applied the hpp-fcl to check collision between a sphere and a cylinder (w/  various rotation/translation).
But, it seems incorrrect result  when a sphere move around a cylinder ;  close  and recede cases (ex. sweep from left to right and vice versa):  no symmetric collision  result.
Sphere and cylinder can have various poses (it move w/ any position and orientation).
I'll debug or investigate my mistakes. 
  -  collide functuon in collision.h  is used

I should be grateful if anyone guide me how to check collision in this case.

**Comment by jcarpent** [comment]
Unfortunately, we have limited human resources to, at the same time, support, maintain, extend and fully document the library. We are aware that this should help the integration of `hpp-fcl` in other projects than our own.

To move forward on your request, we need external help. 
We can try to help you to provide a simple tiny Python example as you asked, and we will be grateful if you can help us to add more materials as you dive into the framework. Is it fine for you?

**Comment by kshfire** [comment]
> Unfortunately, we have limited human resources to, at the same time, support, maintain, extend and fully document the library. We are aware that this should help the integration of `hpp-fcl` in other projects than our own.
> 
> To move forward on your request, we need external help. We can try to help you to provide a simple tiny Python example as you asked, and we will be grateful if you can help us to add more materials as you dive into the framework. Is it fine for you?

Below is my test set-up. I'll appreciate if anyone teach me how to solve my problem.
  - one sphere and one cylinder
    -- can have various pose

  - every loop  : refer "testShapeIntersection function in https://github.com/humanoid-path-planner/hpp-fcl/blob/devel/test/geometric_shapes.cpp"
    -- sphere and cylinder poses are updated
    -- for simplicity, a sphere is moving w/ various position and orientation
    -- collision_result_.clear()
    -- checkShapeIntersection(sphere_geometry_.get(), sphere_pose, cylinder_geometry_.get(), cylinder_pose)
      * bool b_collision = (hpp::fcl::collide(sphere, tf1, cylinder, tf2, collision_request_, collision_results_) > 0)

When I monitored b_collision, there were wrong collision results depending on the sphere pose.  **What did I do wrong ?**
I'm currently analyzing the related HPP-FCL code, but any help would be appreciated.
