### ISSUE TITLE
Proper way to take advantage of convex mesh files in BVH Model

### ISSUE THREAD

**Issue by JeffHough** [humanoid-path-planner/hpp-fcl#340]
I'm currently using `hpp-fcl` to perform collision detection on non-convex shapes, which I have broken down into several convex meshes. I then group together these convex meshes into `hpp::fcl::BVHModel<hpp::fcl::OBBRSS>` models to create collision objects, and perform the collision checks using the `hpp::fcl::DynamicAABBTreeCollisionManager` broadphase collision manager (these are the settings which I have found to have the highest speed).

I recently noticed that `hpp::fcl` supports a `Convex` primative type. Presumably, this would use a better support function at the narrowphase level, and give a pretty significant speed boost compared to assuming all the meshes may be non-convex. 

Given that my mesh files are all convex, I would like to leverage this speed boost. What I have found so far is that the `BVHModel` itself has a `buildConvexRepresentation` method. However, it would seem this method represents the **entire object** as convex, rather than the submeshes as convex, and it causes incorrect results in my case (as I said, the overall objects are **not** convex).

Basically, my current code looks something like this:
```
  using Model = hpp::fcl::BVHModel<hpp::fcl::OBBRSS>;

  // Creation of the collision objects:
  for (int i = 0 ; i < number_of_rigid_bodies ; ++i) {
    auto rigid_body = std::make_shared<Model>();
    rigid_body->beginModel();

    for (const auto& mesh_file : mesh_files) {
      // Load in the object_geometry geometry:
      rigid_body->addSubModel(mesh_file.vertices, mesh_file.triangles);
    }
    rigid_body->endModel();

    // Use the meshes above to create a new collision object
    rigid_bodies[i] = new fcl::CollisionObject(rigid_body, Eigen::Matrix4d::Identity());

    // Compute the axis-aligned bounding box of the new object as a whole:
    rigid_bodies.back()->computeAABB();
  }
```
And I would like to tell `hpp::fcl` to treat the lowest level meshes as convex, so changing this line:
```
rigid_body->addSubModel(mesh_file.vertices, mesh_file.triangles);
```
to something like this:
```
rigid_body->addSubModel(/* some hpp::fcl::convex object */ ....);
```

Is this possible? Is there some other method to leverage the convexity of the mesh files?

Thanks for your help!!

**Comment by jcarpent** [comment]
FCL only support collision checking between convex shapes. 
So, I would say that you should always keep sub-convex meshes separated one from each other and then do the collision checking between this collection of convex meshes and the another shape.

You can use the broad phase to only keep the relevant sub-convex meshes to check during the narrowphase.

The `buildConvexRepresentation` use QHULL to build an outer convex approximation of the given BVHModel because a BVHModel is only composed of a collection of triangles. BVHModel are thus considered as surfaces, not necessarily as volume.

So, if you know your convex objects, then you should directly use the Convex type of hpp-fcl to represent them.
Then, you will be able to perform collision or distance checking using the internal GJK or its variants.

**Comment by JeffHough** [comment]
@jcarpent 

Thank you again for your very fast response!

I see - so would that mean if I have 10 convex mesh files that, when put together, represent a single "real-world" non-convex object, then I should actually be building 10 _different_ collision objects, each using a type "convex"?

I guess when I go to update the transformation of the "real-world" object, I would have to individually update the transformation of each of the 10 convex `CollisionObject`s that represent that object?

**Comment by jcarpent** [comment]
Yes, exactly. We do not yet have something like a compound mesh structure data to do that automatically. This would be interesting to add in the future when the project will also include vhacd linkages.

**Comment by JeffHough** [comment]
Cool! Thanks again for all your help!

Also, I'm just going to toss some thoughts below, that might be completely worthless depending on how the existing software is written... anyways, just some ideas :)

Besides using a compound mesh structure, could a more flexible approach be to use some kind of `CollisionObjectCompound`? 

I.e., I could create a bunch of collision objects (out of mesh files, or as `convex` types, or as the primitive `box` or `sphere` or whatever mix of all of them), and then group them together in a way that they share a transformation, and are included as part of some container `CollisionObjectCompound`, which could have a bounding volume. The "collision checks" on the `CollisionObjectCompound` would then just be a check on the bounding volume, and if colliison is found, then checks on the children of the `CollisionObjectCompound` would be done.

To be honest, that was what I _thought_ the `BVHModel` was doing before I got digging into it a bit more.

As an aside, I'm not sure if these ideas relate at all to issue #128 ?

**Comment by jcarpent** [comment]
Yes, your suggestion makes totally sense and should be easy to do, but requires some bandwidth for that.


> As an aside, I'm not sure if these ideas relate at all to issue #128 ?

This is another story to implement a tree related to BV hierarchy which could be more compact.

**Comment by jcarpent** [comment]
@JeffHough If you are willing to help us on the compound geometry, your contribution is more than welcome. We may organize a call to discuss, with @jmirabel and @lmontaut at least.

**Comment by JeffHough** [comment]
@jcarpent I'd be happy to contribute! I also have pretty limited bandwidth at the moment, so it might be a bit of a slow contribution. I'd also be interested in a call - I could maybe do an evening next week? Feel free to reach me at my email address if you'd like (jeff.hough@maerobotics.com).

**Comment by jmirabel** [comment]
Put me in cc if you plan something. I'll join if I can.
