### ISSUE TITLE
Sphere-sphere normal is nan during collision

### ISSUE THREAD

**Issue by EpicDuckPotato** [humanoid-path-planner/hpp-fcl#344]
I'm trying to compute the normal vector between two intersecting spheres using computeDistances, and whenever I set their positions such that the min_distance <= 0, the normal vector is computed as nan. If I try the same experiment with a sphere and a box, I get a sensible normal vector.

```
import hppfcl
import numpy as np

sphere1_pos = np.array([-0.9, 0, 0])
sphere1_rmat = np.eye(3)
sphere1_rad = 0.5
sphere1_geom = hppfcl.Sphere(sphere1_rad)
sphere1_obj = hppfcl.CollisionObject(sphere1_geom, sphere1_rmat, sphere1_pos)

sphere2_pos = np.zeros(3)
sphere2_rmat = np.eye(3)
sphere2_rad = 0.5
sphere2_geom = hppfcl.Sphere(sphere2_rad)
sphere2_obj = hppfcl.CollisionObject(sphere2_geom, sphere2_rmat, sphere2_pos)

# Distance computation between sphere1 and sphere2
req = hppfcl.DistanceRequest(True)
res = hppfcl.DistanceResult()
distance = hppfcl.distance(sphere1_obj, sphere2_obj, req, res)
print(res.normal) # Prints [nan, nan, nan]

box_pos = np.zeros(3)
box_rmat = np.eye(3)
box_size = 1.0
box_geom = hppfcl.Box(box_size, box_size, box_size)
box_obj = hppfcl.CollisionObject(box_geom, box_rmat, box_pos)

# Distance computation between sphere1 and box
req = hppfcl.DistanceRequest(True)
res = hppfcl.DistanceResult()
distance = hppfcl.distance(sphere1_obj, box_obj, req, res)
print(res.normal) # Prints [1., 0., 0.]
```

**Comment by jmirabel** [comment]
Indeed, I checked the code and the normal is not set.

Could you open a PR with a fix ? It is rather straightforward. If you do it, take care of the convention. I don't remember which one it is and it is not in the doc of `DistanceResult::normal`. Maybe @lmontaut can recall it ?

https://github.com/humanoid-path-planner/hpp-fcl/blob/fbe8d0062c98a358eabf210c94b9ba32b0846eef/src/distance/sphere_sphere.cpp#L56

**Comment by jcarpent** [comment]
This should be fixed in branch hppfcl3x ;)
