### ISSUE TITLE
Feature Request: Pickling

### ISSUE THREAD

**Issue by JonathanKuelz** [humanoid-path-planner/hpp-fcl#356]
Dear hpp-fcl developers,

first of all, thanks for your work on the library! I am using the Python wrappers of hpp-fcl on robotics applications. There, for parallelization, e.g multiple simulations in "clones" of environments containing hpp-fcl obstacles, I want to perform parallel computations which afaik, require objects to be pickle-serializable.

I don't know how much work it would be to add support for python pickle serialization to hpp-fcl objects, but it would be greatly appreciated if someone could add it. I am happy to assist, though I would not be able to implement this feature on my own as I am developing in Python only usually.

**Comment by jcarpent** [comment]
As we already have the support for Boost.Serialization, it should be fast to handle the Pickling as in Pinocchio. Could you give us some hints in which context do you plan to use hpp-fcl?

**Comment by JonathanKuelz** [comment]
I am using pinocchio and hpp-fcl in the context of a toolbox for modular robot simulations: https://gitlab.lrz.de/tum-cps/timor-python

Mostly, I am using it to model static obstacles in task environments (environments I want to perform pick-and-place-like tasks with different manipulators built from modules).

**Comment by jcarpent** [comment]
Solved via #363.
