### ISSUE TITLE
Performance compared to fcl

### ISSUE THREAD

**Issue by simonschmeisser** [humanoid-path-planner/hpp-fcl#376]
I added an initial PR for using hpp-fcl as a collision detector in MoveIt: https://github.com/ros-planning/moveit/pull/3336

Now it seems that in my benchmarks hpp-fcl is slower than fcl in most cases. Is that expected? Am I doing something wrong? Do you have general ideas what I could look for to improve MoveIt's collision checking performance?

The strategy that is currently copied from the fcl plugin is to first do a self-collision check and then do a collision check between each of the robots links and the environment (in form of a pre-computed BVH)

**Comment by jcarpent** [comment]
Dear @simonschmeisser,

This is a very nice initiative.
I did a quick reading of your code, and it seems, in general, you use `hpp::fcl::collide` or `hpp::fcl::distance` functions to perform the operations. Yet, HPP-FCL is much more efficient by deploying caching mechanisms and functors, as done in Pinocchio (https://github.com/stack-of-tasks/pinocchio/blob/c7530c9731095f6f3e5164ac8e4b925987079f39/src/multibody/geometry.hxx#L50-L62). In addition, you did not activate the acceleration procedures as presented [here](https://arxiv.org/abs/2205.09663).

Another benchmark has been performed https://github.com/humanoid-path-planner/hpp-fcl/issues/318#issuecomment-1188634554 and has shown substantial performance gains.

Could you provide the set of basic primitives and meshes you use in your benchmarks? It would be nice to first try to replicate the approach without the additional layer you have added. Indeed, it might be one reason for the limited performances.

**Comment by simonschmeisser** [comment]
Thanks for your quick feedback @jcarpent I'll try to read up on it and see what I can implement.

Benchmarks were done using https://github.com/captain-yoshi/moveit_benchmark_suite

it currently supports the MoveIt API only ( https://github.com/captain-yoshi/moveit_benchmark_suite/blob/master/core/src/scene.cpp ) but there are plans to add support for tesseract and possibly Pinocchio?

**Comment by jmirabel** [comment]
Let's go one by one. Could you report the result for one of the object pairs ? It's usually simpler to compare results for primitive shapes.

Eventually some pointers to the code would help if it's not too buried.

Last question, how did you install the two libraries?

**Comment by jcarpent** [comment]
@simonschmeisser any news?

**Comment by jcarpent** [comment]
I will close this issue as there is no more activity. @simonschmeisser feel free to reopen it.

**Comment by jcarpent** [comment]
Solved via #478
