### ISSUE TITLE
Implement BUILD_TESTING flag in root CMakeLists.txt

### ISSUE THREAD

**Issue by kylesemelka-figure** [humanoid-path-planner/hpp-fcl#377]
There should be a CMake argument to prevent building the tests. The advantage of adding this would be reducing the build dependencies by two: boost::unit_test_framework and boost::timer.

This flag is already implemented in the `test/CMakeLists.txt` file to prevent building the benchmark executable. Why not implement it in the root CMakeLists.txt file instead, so that the user doesn't have to pull in these dependencies if they don't want tests?

**Comment by florent-lamiraux** [comment]
Have you tested with option `-DBUILD_TESTING=OFF` ?

**Comment by jcarpent** [comment]
I guess @kylesemelka-figure wants to refer to something like:
https://github.com/jcarpent/hpp-fcl/blob/a2ec3ad7974809125df198d6cd68da8cc329df1c/CMakeLists.txt#L270-L272
as suggested in #378

**Comment by jcarpent** [comment]
This fix allows to remove then dependency to Boost.UnitTest indeed.

**Comment by jcarpent** [comment]
Solved via #378.
Thanks @kylesemelka-figure for the useful report.
