### ISSUE TITLE
additional constructor for collisionrequest is a bad idea

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-fcl#39]
https://github.com/humanoid-path-planner/hpp-fcl/commit/6732f6962e6f352a2853e304b0cbc447989e596e

Because of the default parameter signature in the other constructor, and 
because bool and size_t  can be used indifferently, the constructor called is undefined
depending on the parameters given. As a matter of fact, the constructor called 
in CollisionValidation is not the one you think. This leads to a bug where max_num_contacts parameter
is in fact set to 0. I am creating a pull request to fix this in hpp-core, but the ambiguity should be removed

**Comment by florent-lamiraux** [comment]
If you are true, there should be a compilation warning.

**Comment by jmirabel** [comment]
I would be in favor of using flags rather than constructors with a series of booleans.
I find `CollisionRequest (Contact | DistanceLowerBound, 1)` more readable than `CollisionRequest (true, 1, true)`...

**Comment by stonneau** [comment]
Well if you create a collision request you should see a warning stating that max_num_contacts is 0. I spotted it in the rb-rrt test of hpp-rbrm, because I was expecting collisions that did not occur.

ps: depending on the compiler you don't always get a compilation warning in such cases, in particular with default constructors.

See for instance a more complex case:

http://www.gotw.ca/gotw/005.htm
________________________________
De : Joseph Mirabel <notifications@github.com>
Envoyé : mardi 8 janvier 2019 13:49
À : humanoid-path-planner/hpp-fcl
Cc : stonneau; Author
Objet : Re: [humanoid-path-planner/hpp-fcl] additional constructor for collisionrequest is a bad idea (#39)


I would be in favor of using flags rather than constructors with a series of booleans.
I find CollisionRequest (Contact | DistanceLowerBound, 1) more readable than CollisionRequest (true, 1, true)...

**Comment by florent-lamiraux** [comment]
I meant that the constructor that is called is deprecated. The compiler should complain or call the other one.

**Comment by stonneau** [comment]
In this case my pull request should not be merged.
________________________________
De : Florent Lamiraux <notifications@github.com>
Envoyé : mardi 8 janvier 2019 13:55
À : humanoid-path-planner/hpp-fcl
Cc : stonneau; Author
Objet : Re: [humanoid-path-planner/hpp-fcl] additional constructor for collisionrequest is a bad idea (#39)


I meant that the constructor that is called is deprecated. The compiler should complain or call the other one.

**Comment by florent-lamiraux** [comment]
I agree with Joseph.

**Comment by stonneau** [comment]
Here it is:
https://github.com/humanoid-path-planner/hpp-fcl/pull/54
