### ISSUE TITLE
Install of binaries distributed via ROS PPA has wrong prefix

### ISSUE THREAD

**Issue by LFric** [humanoid-path-planner/hpp-fcl#392]
Hi,

I am trying to install the package hpp-fcl via the binaries distributed via the ROS PPA. I am using `sudo apt install ros-$ROS_DISTRO-hpp-fcl`. I have ros noetic installed on an ubuntu 20.04 system.

My issue is when I try to build my ros package that depend on hpp-fcl I get the following error:
```
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:300 (message):
  catkin_package() absolute include dir
  '/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig/../../include' does not
  exist
```
The issue comes from the file `/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig/hpp-fcl.pc`.
Below, you can see the content of the file after the install:
```
prefix=${pcfiledir}/../..
exec_prefix=${pcfiledir}/../..
libdir=${pcfiledir}/../../lib/x86_64-linux-gnu
bindir=${pcfiledir}/../../bin
pkglibdir=${pcfiledir}/../../lib/x86_64-linux-gnu/hpp-fcl
includedir=${pcfiledir}/../../include
datarootdir=${pcfiledir}/../../share
pkgdatarootdir=${pcfiledir}/../../share
docdir=
doxygendocdir=

Name: hpp-fcl
Description: HPP fork of FCL -- The Flexible Collision Library
URL: https://github.com/humanoid-path-planner/hpp-fcl
Version: 2.2.0
Requires: eigen3 >= 3.0.0, octomap >= 1.6
Conflicts:
Libs: -L${libdir}  -lhpp-fcl
Libs.private:
Cflags:  -I${includedir} -DHPP_FCL_HAS_OCTOMAP -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=9 -DOCTOMAP_PATCH_VERSION=8
``` 
For example, since `${pcfiledir}` is `/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig`, the `includedir` is then `/opt/ros/noetic/lib/include` when it should be `/opt/ros/noetic/include`.

Does anyone know how to solve this issue without having to manually change the paths in the `hpp-fcl.pc` file ?

**Comment by wxmerkt** [comment]
Hi @LFric,
Sorry to hear you are experiencing this. I believe this is similar to the issue with Pinocchio when using pkg-config. A suitable workaround would be to use the CMake targets, i.e. `find_package(hpp-fcl REQUIRED)` and link against the targets rather than to use pkg-config. Would that work?

**Comment by nim65s** [comment]
@wxmerkt : This could probably be fixed in https://github.com/jrl-umi3218/jrl-cmakemodules/blob/e319590e7c73bbe22b86108031722a134d13349b/pkg-config.cmake#L56-L57

If ROS tools define a CMake variable, we could add a switch on it to add another level of `../`

**Comment by wxmerkt** [comment]
Could it deduce the relative path based on the defined LIBDIR etc. variables automagically?

**Comment by nim65s** [comment]
Yes, thanks for the idea, I'll try to implement that.
