### ISSUE TITLE
[libccd] how to use ccd?

### ISSUE THREAD

**Issue by YongcanZhou** [humanoid-path-planner/hpp-fcl#395]
"In New features: a dedicated and efficient implementation of the GJK algorithm (we do not rely anymore on [libccd](https://github.com/danfis/libccd))"

If I want to use the ccd(continuous collision detection) method to calculate the precise collision time，is there still an interface?

**Comment by florent-lamiraux** [comment]
There is an implementation of continuous collision detection in https://humanoid-path-planner.github.io/hpp-doc/ based on hpp-fcl.

**Comment by jcarpent** [comment]
@florent-lamiraux Could you provide a link to the doc of this function or its implementation?
I guess in the case of hpp, you need to knows the underlying kinematic tree? This is not something object-centric?

**Comment by florent-lamiraux** [comment]
The following paper describes the algorithm: https://hal.laas.fr/hal-04056297.
