### ISSUE TITLE
Compilation error on distance_sphere_sphere.cpp

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-fcl#40]
For some reason, on my ubuntu 16.04 compiler, the code does not compile here

https://github.com/humanoid-path-planner/hpp-fcl/blob/d1f9736427f089a34aea862d764b030fbeabc4c2/src/distance_sphere_sphere.cpp#L75

I get the follwing error: 
operands to ?: have different types ‘const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<double>, const Eigen::Matrix<double, 3, 1> >’ and ‘fcl::Vec3f {aka Eigen::Matrix<double, 3, 1>}’
     Vec3f unit (dist > epsilon ? c1c2/dist : Vec3f (0,0,0));
                                
I understand that normalized is not called to avoid computing the norm twice, still I wonder whether just calling the eigen method would not simplify the code (and selfishly answer my compilation issue).

I propose this modification here, let me know if you disagree, in which case we need to extend the code by computing the quotient outside of the ? operator

https://github.com/stonneau/hpp-fcl/commit/0fd383ed17448480a343b3c503ad54760e83d959

**Comment by florent-lamiraux** [comment]
The result is not exactly equivalent: eigen will normalize whenever dist != 0.
This can lead to unstable behaviors for small "dist" that are not exactly 0.
Can't you simply replace ? by a if ?

**Comment by stonneau** [comment]
I can, I did not think that using this particular epsilon was actually a requirement
________________________________
De : Florent Lamiraux <notifications@github.com>
Envoyé : mardi 8 janvier 2019 17:00
À : humanoid-path-planner/hpp-fcl
Cc : stonneau; Author
Objet : Re: [humanoid-path-planner/hpp-fcl] Compilation error on distance_sphere_sphere.cpp (#40)


The result is not exactly equivalent: eigen will normalize whenever dist != 0.
This can lead to unstable behaviors for small "dist" that are not exactly 0.
Can't you simply replace ? by a if ?

**Comment by stonneau** [comment]
fixed by https://github.com/humanoid-path-planner/hpp-fcl/commit/5dc69d63bdc15af00e052b8e7aa0068d88a83c86
