### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#409]
### Discussed in https://github.com/humanoid-path-planner/hpp-fcl/discussions/408

<div type='discussions-op-text'>

<sup>Originally posted by **rayman30011** April 28, 2023</sup>
Hi everyone! I installed hppflc by pip and when I executed import hppfcl, an error occurs
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cmeel.prefix/lib/python3.11/site-packages/hppfcl/__init__.py", line 34, in <module>
    from .hppfcl import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cmeel.prefix/lib/python3.11/site-packages/hppfcl/hppfcl.cpython-311-darwin.so, 0x0002): Symbol not found: __ZN7eigenpy9NumpyType7getTypeEv
  Referenced from: <D6D22B7C-0254-3FF5-B18B-FDFEB1934343> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cmeel.prefix/lib/python3.11/site-packages/hppfcl/hppfcl.cpython-311-darwin.so
  Expected in:     <32DE8AFB-233E-3DED-B68D-08B4E598996D> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cmeel.prefix/lib/libeigenpy.dylib`
  
  Did someone encountered something similar/knows how to fix it? macOS 13.3.1 m1
  Thanks!
 </div>

**Comment by jcarpent** [comment]
We will fix this issue soon. 
@rayman30011 In the meantime, you can install hpp-fcl using conda on mac os x.
It should work as a charm.

**Comment by rayman30011** [comment]
Not working(
`cmeel==0.41.1
cmeel-assimp==5.2.5
cmeel-boost==1.81.0
cmeel-octomap==1.9.8.1
eigenpy==3.0.0
hpp-fcl==2.2.0
numpy==1.24.3
tomli==2.0.1`

**Comment by nim65s** [comment]
@rayman30011 : this should be fixed. I'm using cirrus-CI for those builds, and they oldest available version is monterey, and it is not building correctly anymore for python 3.8. 

So now, we only have builds for python > 3.9, but it looks like this is working again. Could you confirm this with your 3.11, and close this issue if it is OK ?

**Comment by rayman30011** [comment]
Great! close this issue
