### ISSUE TITLE
FCL building in Github Actions uses wrong Python version

### ISSUE THREAD

**Issue by rayzchen** [humanoid-path-planner/hpp-fcl#426]
https://github.com/humanoid-path-planner/hpp-fcl/actions/runs/5054289798/jobs/9069053579#step:5:61, but the action for setup-miniconda is given and correctly sets up Python 3.7 (https://github.com/humanoid-path-planner/hpp-fcl/actions/runs/5054289798/jobs/9069053579#step:3:466)

**Comment by rayzchen** [comment]
I don't think that is going to fix the problem, since it is still using Python 3.11 and disregarding the `python-version` option.

**Comment by rayzchen** [comment]
Is there a particular reason why `goanpeca/setup-miniconda` is used instead of `conda-incubator/setup-miniconda`?

**Comment by jcarpent** [comment]
Except for historical reasons, no. I've just changed it.

**Comment by jcarpent** [comment]
Fixed via #427.

**Comment by rayzchen** [comment]
I believe it still is creating a Python 3.11 module, since https://github.com/humanoid-path-planner/hpp-fcl/actions/runs/5122067821/jobs/9210618055#step:5:8654 shows that it cannot find `hppfcl.hppfcl`, which should point to a file called `hppfcl.cp310-win_amd64.pyd`, but the file found there (from my fork of this repo that saves the generated Python files) is called `hppfcl.cp311-win_amd64.pyd`.

**Comment by rayzchen** [comment]
Also, running `%CONDA_PREFIX%\python -V` prints `Python 3.11.0`.
https://github.com/rayzchen/hpp-fcl/actions/runs/5122655127/jobs/9212038941#step:6:56

**Comment by jcarpent** [comment]
Perfect. Thanks for the report. I was only looking at the cmake configuration.
I will look at it.

**Comment by rayzchen** [comment]
Sorry, my bad, my fork had merge conflicts which weren't resolved correctly and still used v1 of the `setup-miniconda` action. Once fixed, the correct version of Python was used. It seems that I tried to link two separate problems together.
