### ISSUE TITLE
Classes named `class ClassName` generated in python stub file

### ISSUE THREAD

**Issue by rayzchen** [humanoid-path-planner/hpp-fcl#435]
The `__all__` of `hppfcl/__init__.pyi` (generated by pybind11) has these elements:
```
    "class DynamicAABBTreeArrayCollisionManager",
    "class DynamicAABBTreeCollisionManager",
    "class IntervalTreeCollisionManager",
    "class NaiveCollisionManager",
    "class SSaPCollisionManager",
    "class SaPCollisionManager",
```
These 6 classes are defined as `class class DynamicAABBTreeArrayCollisionManager` etc.
This means that linters cannot read the stub file correctly.

**Comment by jcarpent** [comment]
@rayzchen I guess you are on Windows. Which version of hpp-fcl do you use (`python -c "import hppfcl; print(hppfcl.__version__)"`). The issue should have been fixed via 13438ee6 and released in v2.3.4. Could you confirm?

**Comment by rayzchen** [comment]
I am using `2.3.3` currently, will test `2.3.4` tomorrow.

**Comment by rayzchen** [comment]
Issue has been fixed, not sure why hppfcl didn't update correctly.
