### ISSUE TITLE
RuntimeError: Library built without qhull. Cannot build object of this type.

### ISSUE THREAD

**Issue by fb1812** [humanoid-path-planner/hpp-fcl#447]
I keep running into this error, but everything seems to be built correctly. 
Anyone that can help? 

Thank you!

**Comment by fb1812** [comment]
Yes, but i keep running on this issue :

python3 geometric_shapes.py 
....QH6249 qh_lib_check: Incorrect qhull library called.  Size of qhT for caller is 8184, but for qhull library is 8768.
QH6259 qhull internal error (qh_lib_check): Cannot continue due to QH6249.  'qhull_r 8.1-alpha3 (2020.2.r 2023/01/02)' is not reentrant (e.g., qhull.so) or out-of-date.  Exit with 49


Any idea of what is causing this? 

Thank you !

**Comment by nim65s** [comment]
How did you install qhull on your system ?

**Comment by fb1812** [comment]
I followed the instruction from here https://github.com/qhull/qhull/tree/5a79a0009454c86e9848646b3c296009125231bf

**Comment by jcarpent** [comment]
@fb1812 Could you provide a docker image reproducing your issue?
