### ISSUE TITLE
Segmentation Fault when using with Pinocchio

### ISSUE THREAD

**Issue by lwygzh** [humanoid-path-planner/hpp-fcl#466]
Hi,

I noticed a weird bug. If I run

```python
import hppfcl
import pinocchio as pin
import numpy as np

R = pin.Quaterion(np.eye(3))
```

I will get a segmentation fault

```bash
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hppfcl
>>> import pinocchio as pin
>>> import numpy as np
>>> pin.Quaternion(np.eye(3))
[1]    209779 segmentation fault (core dumped)  python3
```

Would it be possible to take a look into this?

**Comment by jcarpent** [comment]
Could you please provide a docker file to reproduce your issue ?

**Comment by lwygzh** [comment]
Sorry for the late response, after debugging, I think the issue is with my own conda environment, I could not reproduce it outside of it. I will close this issue.
