### ISSUE TITLE
How to compile in Windows?

### ISSUE THREAD

**Issue by Rennngw** [humanoid-path-planner/hpp-fcl#469]
Hello, I tried to compile hpp-fcl on the windows system. I used cmake-gui VS2022 to compile, and the following error occurred. How can I solve this problem?

![image](https://github.com/humanoid-path-planner/hpp-fcl/assets/110526351/3d95512f-a197-4f01-9a10-263604712074)

**Comment by jcarpent** [comment]
You can use conda to install on Windows.
```bash
conda install hpp-fcl -c conda-forge
```

**Comment by jcarpent** [comment]
Do you really need to compile from source?
