### ISSUE TITLE
Namespace change

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-fcl#51]
For external use of hpp-fcl, it might be a good idea to change the namespace.

Currently, an application which would load both libfcl.so and libhpp-fcl.so (even indirectly) will likely crash because of functions have the same prototype.

**Comment by jmirabel** [comment]
The most homogeneous solution is to wrap everything into namespace hpp.

**Comment by stonneau** [comment]
As long as we agree that this requires a change of version :)

**Comment by jmirabel** [comment]
@stonneau Yes, it will. I believe this won't impact you so much because your code is in the hpp namespace.

**Comment by wxmerkt** [comment]
@jmirabel can you please ping me once this is done so I can make the release? Thank you :)

**Comment by wxmerkt** [comment]
Thank you for merging @nim65s. Are you intending to release as 0.8?

**Comment by nim65s** [comment]
No, this will be v1.0.0, I'm finalizing it.

**Comment by nim65s** [comment]
@wxmerkt done. I think you can now release it to ROS if you still want to :)
