### ISSUE TITLE
make error: Eigen 'Vector' template error 

### ISSUE THREAD

**Issue by iamnambiar** [humanoid-path-planner/hpp-fcl#551]
Hi. I am trying to build the repository for a project, but I am facing an issue when running `make` command.

<pre><b>/home/projects/hpp-fcl/test/normal_and_nearest_points.cpp:244:8:</b> <font color="#CC0000"><b>error: </b></font>‘<b>Vector</b>’ in namespace ‘<b>Eigen</b>’ does not name a template type; did you mean ‘<b>VectorXd</b>’?
  244 | Eigen::<font color="#CC0000"><b>Vector</b></font>&lt;FCL_REAL, VecSize&gt; generateRandomVector(FCL_REAL min,
      |        <font color="#CC0000"><b>^~~~~~</b></font>
      |        <font color="#4E9A06">VectorXd</font>
</pre>

The Eigen version I am using is 3.3.7. 

Can someone please advice me a solution for this. Thanks.

**Comment by lmontaut** [comment]
Hi @iamnambiar,
It's my bad, I am using eigen 3.4 (`Eigen::Vector` is not available on 3.3.7).
I will do a PR to change that.
Thanks for reporting the issue!

**Comment by iamnambiar** [comment]
Thank you @lmontaut 

I replaced the error by changing it to  `Eigen::Matrix<FCL_REAL, VecSize, 1>`. Anyway, I am closing this issue as it has been addressed. Thanks.
