### ISSUE TITLE
CI fail on OSX

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-fcl#57]
Hi,

Travis is not happy with OSX build. @jcarpent : do you want to look at it ?
https://travis-ci.org/nim65s/hpp-fcl/jobs/492160707

**Comment by jcarpent** [comment]
It seems that you don't have provided the `operator<` for `CachedMeshLoader::Key` types.

**Comment by jcarpent** [comment]
By the way, I just read the output of travis report ;)

**Comment by nim65s** [comment]
About the master branch, it was clearly a mistake. We can put it back to its previous state.

About the travis report I saw the issue with `operator<`, but as this is not happening on 14.04, 16.04 or 18.04, I don't really understand the error.

**Comment by jmirabel** [comment]
> It seems that you don't have provided the operator< for CachedMeshLoader::Key types.

It is defined but not declared. I am surprised I didn't get an error...

**Comment by jmirabel** [comment]
The fix is here: 632e315

**Comment by jmirabel** [comment]
@nim65s Can you move master to its previous position and remove version 1.0.0 ?

The merge of devel into master will wait a bit.

**Comment by nim65s** [comment]
master is back to its previous state.
About 1.0.0, no, once it is published, it would be the worst idea to remove it, apart from remove it and then make a new one with the same name. We just need to make 1.0.1.

**Comment by jmirabel** [comment]
You shouldn't have published it. It was a mistake and we discovered it quickly. So please, quickly remove this erroneous release.

**Comment by nim65s** [comment]
@wxmerk might have already started work on it, and this release would definitely work for him on ROS. The 1.0.1 will be only useful for OSX, so I don't see the point in risking making this situation even worse.

**Comment by wxmerkt** [comment]
I did work on it and prepare the release but haven't pulled the trigger. I will wait until you guys give the green light that everything is OK - whether that is 1.0.1 or a force-pushed 1.0.0 tag.

**Comment by nim65s** [comment]
the tag and the tar.gz have been removed from this repo, but the next release will be 1.0.1

**Comment by jmirabel** [comment]
Thank you @nim65s

**Comment by nim65s** [comment]
#58 fix the error on the build, but one test is still not passing.

**Comment by jmirabel** [comment]
Is there a way to get the logs of the unit tests to have a more verbose output ?

**Comment by nim65s** [comment]
yes, cf https://github.com/nim65s/hpp-fcl/commit/6ee7fdf6220720ca6d80f8606f2df963eef9d84b

**Comment by nim65s** [comment]
Pushed it 30min ago, travis is still booting a VM to launch them…

**Comment by nim65s** [comment]
Another possibility is to run directly the failing test, eg. `./test/test_fcl_frontlist`

**Comment by nim65s** [comment]
And now the tests are passing https://travis-ci.org/nim65s/hpp-fcl/jobs/492209729
I give up for now :)
