### ISSUE TITLE
Request for new release into ROS 2 Rolling

### ISSUE THREAD

**Issue by clalancette** [humanoid-path-planner/hpp-fcl#612]
This is a request to release the latest code here into ROS 2 Rolling.  I know that you are currently in the process of attempting to rename this library, but it would be great to have a release with https://github.com/humanoid-path-planner/hpp-fcl/pull/598 in it so that we can remove octomap from Rolling.

Please let me know if you need any help with this.  Thanks!

**Comment by jcarpent** [comment]
We have just released a patch release [v2.4.5](https://github.com/humanoid-path-planner/hpp-fcl/releases/tag/v2.4.5)

**Comment by clalancette** [comment]
> We have just released a patch release [v2.4.5](https://github.com/humanoid-path-planner/hpp-fcl/releases/tag/v2.4.5)

Thank you!  Would you mind doing a `bloom-release` for it into Rolling?

**Comment by clalancette** [comment]
Thank you for the releases!
