### ISSUE TITLE
Question: why isFree(), isOccupied() and isUncertain() have been set to deprecated?

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#62]

**Comment by florent-lamiraux** [comment]
of which class ?

**Comment by jcarpent** [comment]
in CollisionGeometry

**Comment by florent-lamiraux** [comment]
These features make sense only for Octree class that has additional methods `isNodeOccupied`, `isNodeFree`, and `isNodeUncertain`. I think some more cleaning is needed. Do you use those methods?
