### ISSUE TITLE
How to calculate correct negative security_margin to pass this assert

### ISSUE THREAD

**Issue by almazgaliev** [humanoid-path-planner/hpp-fcl#621]
my code causes assertion failure in file

hpp-fcl\src\BV\OBB.cpp

```cpp
bool obbDisjointAndLowerBoundDistance(const Matrix3f& B, const Vec3f& T,
                                      const Vec3f& a_, const Vec3f& b_,
                                      const CollisionRequest& request,
                                      FCL_REAL& squaredLowerBoundDistance) {
  assert(request.security_margin >
             -2 * (std::min)(a_.minCoeff(), b_.minCoeff()) -
                 10 * Eigen::NumTraits<FCL_REAL>::epsilon() &&
         "A negative security margin could not be lower than the OBB extent.");
   ...
```

how can i verify security_margin value, which i set into CollisionRequest, if its valid for model?

**Comment by lmontaut** [comment]
Hi @almazgaliev,
HPP-FCL supports negative security margin. That's typically when, in your application, you don't care if two geometries overlap by a certain amount.
On the contrary, when using a positive security margin, you want to ensure the geometries don't overlap, so you put a security around them.

Anyway, the security margin, if it's negative, cannot be "too" negative. This assert checks for that, for two OBBs.
In C++, you can go over the OBBs of your model and check that the security margin passes this test.
In python, I think we didn't expose OBBs yet.

**Comment by almazgaliev** [comment]
Thanks for answering, i need to think about it. Also I need to make sure if i understood code correctly.
`a_`  and `b_`  parameters in this member function contain half of bounding boxes lengths by axis? 
and are those bounding boxes related to primitives like triangles (i think in my case it is since i create BVHModel by vector of vertecies and triangles)? 
i was thinking that if i need security margin to be lower than i can do in this case then maybe i need to reconfigure my model's triangles for it to have lower values of minCoeff?
