### ISSUE TITLE
Are the changes to assimp public?

### ISSUE THREAD

**Issue by wxmerkt** [humanoid-path-planner/hpp-fcl#65]
Is the source repository for `robotpkg-assimp` public, and if so, what is the URL? I noticed issues with `libassimp-dev` on Bionic (wrong include directory) and am wondering what changes and potential fixes are in `robotpkg-assimp`

**Comment by nim65s** [comment]
Hi @wxmerkt 

Most of robotpkg is public, and I have a clone on github here: https://github.com/nim65s/robotpkg

In it, you can find that on all supported system (but Gentoo & NetBSD), robotpkg  prefer to use the version from the distribution: https://github.com/nim65s/robotpkg/blob/master/graphics/assimp/depend.mk

Just to be sure that we understand each other:  the `libassimp-dev` on Bionic should be this one: https://packages.ubuntu.com/bionic/libassimp-dev, and this should be the one used on all our packages (`apt depends robotpkg-hpp-fcl` will show `libassimp-dev` and not `robotpkg-assimp`).

This said, if I understand correctly your question, you have an issue with the official `libassimp-dev` and would like to see if the one provided by robotpkg would be better for you. In this case, the configuration of this robotpkg package is here: https://github.com/nim65s/robotpkg/blob/master/graphics/assimp/Makefile and we added one patch: https://github.com/nim65s/robotpkg/blob/master/graphics/assimp/patches/patch-aa

But this version is 6 years old. We can update it if you need it.

**Comment by nim65s** [comment]
PS: the official repo and issue tracker are here: https://git.openrobots.org/projects/robotpkg

**Comment by wxmerkt** [comment]
Thank you @nim65s for the great pointers and explanation - seeing this makes me wonder what `robotpkg-assimp` is used for when `libassimp-dev` exists?

The issue I have is known upstream has been fixed since December, 2018 (the include directory that is exported includes `/usr/lib/include` [sic!]) -- but as expected has not propagated through (Debian etc.). The issue is thus that it cannot correctly find and export the include directories. 

I'll keep investigating and thank you again for the great response.
