### ISSUE TITLE
Double FCL_HAVE_OCTOMAP

### ISSUE THREAD

**Issue by jcarpent** [humanoid-path-planner/hpp-fcl#79]
Small question: is normal to have both `FCL_HAVE_OCTOMAP`and `HPP_FCL_HAVE_OCTOMAP`?

https://github.com/humanoid-path-planner/hpp-fcl/blob/c83a604f0c9618815ab50761421be0ab22981f40/CMakeLists.txt#L171

**Comment by jmirabel** [comment]
I think it was for backward compatibility.
