### ISSUE TITLE
Provide operator == to class CollisionResult

### ISSUE THREAD

**Issue by fvalenza** [humanoid-path-planner/hpp-fcl#8]
In Pinocchio, i need to perform the comparison operation between two fcl::CollisionResult Objects.

As this struct contains vector of Contact and vector of CostSource, the naive approach consisting of thinking default operators will be defined doesn't work ( I get compiling errors stating that the operator == is invalind between two const fcl::CollisionResult ).
Two ways are then possible :
1/ Perform in Pinocchio in a raw way this comparison, iterating through vectors etc
2/ Provide such operator in fcl::CollisionResult, thus also in Contact and CostSource

**Comment by jcarpent** [comment]
The second solution looks better.
