### ISSUE TITLE
[refactoring] Bindings do not work on Mac

### ISSUE THREAD

**Issue by gabrielebndn** [humanoid-path-planner/hpp-fcl#86]
The `hppfcl` module does not show up on my Mac after installation.
I use a fairly old OS (10.11, El Capitan), but it will likely be the same on newer versions, as far as I understand.
Apparently, there is a problem with the `.dylib` extension. It should be `.so`, even for Mac.

I followed this post:
https://stackoverflow.com/questions/2488016/how-to-make-python-load-dylib-on-osx

For me, it was enough to do `mv hppfcl.dylib hppfcl.so` inside `lib/python2.7/site-packages` and the problem was solved. This should be handled in the CMakeLists.txt

**Comment by jcarpent** [comment]
I think the solution is inside EigenPy and Pinocchio.

**Comment by gabrielebndn** [comment]
@jcarpent for sure. I can see `eigenpy` generates a `.so` file

**Comment by gabrielebndn** [comment]
The problem is still open on my Mac after #87

**Comment by gabrielebndn** [comment]
Solved by #88
