### ISSUE TITLE
Merging the refactoring branch to devel

### ISSUE THREAD

**Issue by gabrielebndn** [humanoid-path-planner/hpp-fcl#92]
I am writing this issue to keep track of what is missing for the refactoring branch to be mature enough for a release.
So far, I can identify:
- [x] Handle redundancy between `lz` and `HalfLength` in `Cylinder`, `Capsule` and `Cone`. This can be done by either removing `lz` or by making the variables private and providing appropriate getter/setter methods which ensure consistency between the two values
- [x] Fix the CI failure in unit test `frontlist`. As far as I have understood, the buggy feature could be removed altogether
- [x] Expand the Python bindings so that they cover at least all classes and methods currently exposed in Pinocchio and the most important core algorithms
- [ ] Verify the Python bindings through appropriate unit tests
- [x] Install internal headers.
- [x] Run integration test for known dependencies (pinocchio and HPP)

@jmirabel, I know you have something to add to the list. Feel free to edit this post
@nmansard, could you provide feedback of what you need to be exposed for your tutorials?

**Comment by jmirabel** [comment]
@LucileRemigy could you take care of the first item ?

**Comment by jmirabel** [comment]
The integration test and the Python bindings unit-tests are not blocking the merging of refactoring into devel. I will do the merge before doing the integration test so that people can start playing with the new features and eventually report issues.

**Comment by jcarpent** [comment]
Test are passing well on my machine. You can proceed to the merging I think.

**Comment by jmirabel** [comment]
I tested it on HPP. There is one tricky change in class Transform3f which had impact in 2/3 places. The code compiles and I think the semantic is correct. I didn't run the benchmarks. I merge this now.

**Comment by gabrielebndn** [comment]
I am fixing a couple of things. Please wait a minute

**Comment by gabrielebndn** [comment]
The refactoring branch has been merged. All points are satisfied, except for the unit tests for the Python bindings. There are already tests for the bindings which are interesting to me, the rest can be addressed in the long term. I think this issue can be closed.
